packages:
  - packages/*
  - apps/ddaas

catalog:
  '@changesets/cli': ^2.29.8
  '@clerk/localizations': ^3.37.2
  '@clerk/nextjs': ^6.39.0
  '@clerk/themes': ^2.4.57
  '@clerk/types': ^4.101.20
  '@fingerprintjs/fingerprintjs': ^5.1.0
  '@hookform/resolvers': ^5.2.2
  '@radix-ui/react-accordion': ^1.2.10
  '@radix-ui/react-alert-dialog': ^1.1.13
  '@radix-ui/react-aspect-ratio': ^1.1.6
  '@radix-ui/react-avatar': ^1.1.9
  '@radix-ui/react-checkbox': ^1.3.1
  '@radix-ui/react-collapsible': ^1.1.10
  '@radix-ui/react-context-menu': ^2.2.14
  '@radix-ui/react-dialog': ^1.1.13
  '@radix-ui/react-dropdown-menu': ^2.1.14
  '@radix-ui/react-hover-card': ^1.1.13
  '@radix-ui/react-label': ^2.1.6
  '@radix-ui/react-menubar': ^1.1.14
  '@radix-ui/react-navigation-menu': ^1.2.12
  '@radix-ui/react-popover': ^1.1.13
  '@radix-ui/react-progress': ^1.1.6
  '@radix-ui/react-radio-group': ^1.3.6
  '@radix-ui/react-scroll-area': ^1.2.8
  '@radix-ui/react-select': ^2.2.4
  '@radix-ui/react-separator': ^1.1.6
  '@radix-ui/react-slider': ^1.3.4
  '@radix-ui/react-slot': ^1.2.2
  '@radix-ui/react-switch': ^1.2.4
  '@radix-ui/react-tabs': ^1.1.11
  '@radix-ui/react-toast': ^1.2.13
  '@radix-ui/react-toggle': ^1.1.8
  '@radix-ui/react-toggle-group': ^1.1.9
  '@radix-ui/react-tooltip': ^1.2.6
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-commonjs': 28.0.6
  '@rollup/plugin-node-resolve': 16.0.1
  '@rollup/plugin-typescript': 12.1.4
  '@prisma/client': ^6.17.1
  '@tailwindcss/cli': ^4.2.1
  '@tailwindcss/postcss': ^4.2.1
  '@tailwindcss/typography': latest
  '@types/fs-extra': ^11.0.4
  '@types/hast': ^3.0.4
  '@types/mdx': ^2.0.13
  '@types/node': ^25.3.2
  '@types/nprogress': ^0.2.3
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@types/react-medium-image-zoom': ^3.0.3
  '@typescript-eslint/parser': ^8.56.1
  '@upstash/redis': ^1.34.0
  '@upstash/qstash': ^2.7.0
  '@upstash/lock': ^0.2.1
  autoprefixer: ^10.4.27
  chokidar: ^3.5.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commander: ^12.0.0
  cmdk: 1.0.4
  date-fns: ^4.1.0
  embla-carousel-react: 8.5.1
  eslint: ^9.39.1
  eslint-config-next: ^16.1.6
  eslint-plugin-unused-imports: ^4.4.1
  fast-glob: ^3.3.3
  fs-extra: ^11.2.0
  fumadocs-core: 16.0.9
  fumadocs-docgen: 3.0.4
  fumadocs-mdx: 13.0.6
  fumadocs-typescript: 4.0.13
  fumadocs-ui: 16.0.9
  glob: ^10.4.5
  input-otp: 1.4.2
  katex: ^0.16.33
  lucide-react: ^0.575.0
  mermaid: 11.12.1
  next: 16.1.6
  next-intl: ^4.8.3
  next-themes: ^0.4.6
  nprogress: ^0.2.0
  picocolors: ^1.0.0
  postcss: ^8.5.6
  postcss-cli: ^11.0.1
  prisma: ^6.17.1
  react: 19.2.4
  react-day-picker: 8.10.1
  react-dom: 19.2.4
  react-medium-image-zoom: ^5.4.1
  react-resizable-panels: ^2.1.9
  recharts: 2.15.3
  rehype-katex: ^7.0.1
  remark: ^15.0.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  remark-math: ^6.0.0
  remark-mdx: ^3.1.0
  rollup: 4.46.2
  rollup-plugin-peer-deps-external: ^2.2.4
  rollup-plugin-preserve-directives: ^0.4.0
  shiki: ^4.0.0
  sonner: ^1.7.4
  stripe: 20.0.0
  svix: ^1.86.0
  swiper: ^12.1.2
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.1
  tailwindcss-animate: ^1.0.7
  tslib: ^2.8.1
  ts-morph: 27.0.2
  ts-node: ^10.9.2
  tsup: ^8.3.5
  tsx: ^4.1.0
  turbo: ^2.8.12
  typescript: ^5.8.3
  unist-util-visit: ^5.1.0
  vaul: ^0.9.9
  zod: ^4.3.6

prefer-workspace-packages: true

save-workspace-protocol: true

shared-workspace-lockfile: true
