import { Command } from 'commander'
import { promises as fs } from 'fs'
import path from 'path'

type RouteDef = {
  path: string
  importPath: string
  methods: string[]
  runtime?: 'nodejs' | 'edge' | 'experimental-edge'
  buildContent?: (route: RouteDef) => string
}

type RouteSyncResult = {
  file: string
  status: string
}

const PACKAGE_NAME = '@windrun-huaiin/backend-core'

const ROUTES: RouteDef[] = [
  {
    path: 'webhook/stripe',
    importPath: `${PACKAGE_NAME}/app/api/webhook/stripe/route`,
    methods: ['POST'],
    runtime: 'nodejs'
  },
  {
    path: 'webhook/clerk/user',
    importPath: `${PACKAGE_NAME}/app/api/webhook/clerk/user/route`,
    methods: ['POST']
  },
  {
    path: 'user/anonymous/init',
    importPath: `${PACKAGE_NAME}/app/api/user/anonymous/init/route`,
    methods: ['POST']
  },
  {
    path: 'user/credit-overview',
    importPath: `${PACKAGE_NAME}/app/api/user/credit-overview/route`,
    methods: ['GET'],
    buildContent: buildCreditOverviewRoute
  },
  {
    path: 'user/pricing-context',
    importPath: `${PACKAGE_NAME}/app/api/user/pricing-context/route`,
    methods: ['GET']
  },
  {
    path: 'stripe/checkout',
    importPath: `${PACKAGE_NAME}/app/api/stripe/checkout/route`,
    methods: ['POST']
  },
  {
    path: 'stripe/customer-portal',
    importPath: `${PACKAGE_NAME}/app/api/stripe/customer-portal/route`,
    methods: ['POST']
  }
]

export function registerBackendCoreCommands(program: Command) {
  const backendCore = program
    .command('backend-core')
    .usage('backend-core <subcommand> [options]')
    .description('Integration @windrun-huaiin/backend-core, use "dev-scripts backend-core -h" for more msg')
    .addHelpText(
      'after',
      [
        '',
        'Examples:',
        '  dev-scripts backend-core routes:list',
        '  dev-scripts backend-core routes:sync --app-dir src/app --force',
        '',
        'Defaults:',
        '  routes:sync    --app-dir src/app (generates under <app-dir>/api)',
      ].join('\n')
    )

  backendCore
    .command('routes:sync')
    .description('Generate Next.js route proxy files that re-export backend-core handlers')
    .option('--app-dir <dir>', 'App directory containing api folder', 'src/app')
    .option('--force', 'Overwrite existing files', false)
    .action(async (opts) => {
      const cwd = process.cwd()
      try {
        const results = await syncBackendCoreRoutes(opts.appDir, opts.force, cwd)
        console.log('Routes sync results:')
        for (const r of results) {
          console.log(`- ${r.status} :: ${r.file}`)
        }
      } catch (error) {
        console.error('routes:sync failed:', (error as Error).message)
        process.exitCode = 1
      }
    })

  backendCore
    .command('routes:list')
    .description('List available backend-core routes')
    .action(() => {
      listBackendCoreRoutes()
    })
}

export async function syncBackendCoreRoutes(
  appDirInput: string,
  force: boolean = false,
  cwd: string = process.cwd()
): Promise<RouteSyncResult[]> {
  const appDir = path.resolve(cwd, appDirInput)
  const results: RouteSyncResult[] = []

  for (const route of ROUTES) {
    const targetDir = path.join(appDir, 'api', route.path)
    const targetFile = path.join(targetDir, 'route.ts')
    try {
      await fs.mkdir(targetDir, { recursive: true })
      const exists = await fileExists(targetFile)
      if (exists && !force) {
        results.push({ file: targetFile, status: 'skip (exists)' })
        continue
      }
      const content = buildProxy(route)
      await fs.writeFile(targetFile, content, 'utf8')
      results.push({ file: targetFile, status: exists ? 'overwritten' : 'created' })
    } catch (error) {
      results.push({ file: targetFile, status: `error: ${(error as Error).message}` })
    }
  }

  return results
}

export function listBackendCoreRoutes() {
  console.log('Available backend-core routes (relative to app/api):')
  ROUTES.forEach((route) => {
    console.log(`- ${route.path} [${route.methods.join(', ')}]`)
  })
}

function buildProxy(route: RouteDef): string {
  if (route.buildContent) {
    return route.buildContent(route)
  }

  const exports = [
    ...route.methods.map((method) => `export { ${method} } from '${route.importPath}';`)
  ]
  const runtimeLine = route.runtime ? `export const runtime = '${route.runtime}';` : null
  return [
    '// Auto-generated by dev-scripts backend-core routes:sync',
    '// Do not edit manually unless you want to override the default handler.',
    "import '@/server/prisma';",
    ...exports,
    ...(runtimeLine ? [runtimeLine] : []),
    ''
  ].join('\n')
}

function buildCreditOverviewRoute(route: RouteDef): string {
  return [
    '// Auto-generated by dev-scripts backend-core routes:sync',
    '// Do not edit manually unless you want to override the default handler.',
    '',
    "import '@/server/prisma';",
    "import { defaultLocale, localePrefixAsNeeded } from '@/lib/appConfig';",
    `import { createGET } from '${route.importPath}';`,
    "import type { CreditOverviewTranslations } from '@windrun-huaiin/third-ui/main/credit';",
    "import { getTranslations } from 'next-intl/server';",
    '',
    'export const GET = createGET({',
    '  defaultLocale,',
    '  localePrefixAsNeeded,',
    '  async resolveTranslations(locale) {',
    "    const t = await getTranslations({ locale, namespace: 'credit' });",
    '',
    '    return {',
    "      summaryDescription: t('summary.description'),",
    "      totalLabel: t('summary.totalLabel'),",
    "      bucketsTitle: t('buckets.title'),",
    "      bucketsEmpty: t('buckets.empty'),",
    "      expiredAtLabel: t('buckets.expiredAtLabel'),",
    "      expandDetail: t('buckets.expandDetail'),",
    "      hiddenDetail: t('buckets.hiddenDetail'),",
    "      bucketDefaultLabels: (t.raw('buckets.labels') as Record<string, string>) ?? {},",
    "      subscriptionPeriodLabel: t('subscription.periodLabel'),",
    "      subscriptionManage: t('subscription.manage'),",
    "      subscriptionInactive: t('subscription.inactive'),",
    "      subscribePay: t('subscription.pay'),",
    "      onetimeBuy: t('onetime.buy'),",
    '    } satisfies CreditOverviewTranslations;',
    '  },',
    '});',
    ''
  ].join('\n')
}

async function fileExists(file: string) {
  try {
    await fs.access(file)
    return true
  } catch {
    return false
  }
}
