
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Apilog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Apilog
 * 
 */
export type ApilogModel = runtime.Types.Result.DefaultSelection<Prisma.$ApilogPayload>

export type AggregateApilog = {
  _count: ApilogCountAggregateOutputType | null
  _avg: ApilogAvgAggregateOutputType | null
  _sum: ApilogSumAggregateOutputType | null
  _min: ApilogMinAggregateOutputType | null
  _max: ApilogMaxAggregateOutputType | null
}

export type ApilogAvgAggregateOutputType = {
  id: number | null
}

export type ApilogSumAggregateOutputType = {
  id: bigint | null
}

export type ApilogMinAggregateOutputType = {
  id: bigint | null
  apiType: string | null
  methodName: string | null
  summary: string | null
  request: string | null
  response: string | null
  createdAt: Date | null
}

export type ApilogMaxAggregateOutputType = {
  id: bigint | null
  apiType: string | null
  methodName: string | null
  summary: string | null
  request: string | null
  response: string | null
  createdAt: Date | null
}

export type ApilogCountAggregateOutputType = {
  id: number
  apiType: number
  methodName: number
  summary: number
  request: number
  response: number
  createdAt: number
  _all: number
}


export type ApilogAvgAggregateInputType = {
  id?: true
}

export type ApilogSumAggregateInputType = {
  id?: true
}

export type ApilogMinAggregateInputType = {
  id?: true
  apiType?: true
  methodName?: true
  summary?: true
  request?: true
  response?: true
  createdAt?: true
}

export type ApilogMaxAggregateInputType = {
  id?: true
  apiType?: true
  methodName?: true
  summary?: true
  request?: true
  response?: true
  createdAt?: true
}

export type ApilogCountAggregateInputType = {
  id?: true
  apiType?: true
  methodName?: true
  summary?: true
  request?: true
  response?: true
  createdAt?: true
  _all?: true
}

export type ApilogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Apilog to aggregate.
   */
  where?: Prisma.ApilogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apilogs to fetch.
   */
  orderBy?: Prisma.ApilogOrderByWithRelationInput | Prisma.ApilogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApilogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apilogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apilogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Apilogs
  **/
  _count?: true | ApilogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApilogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApilogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApilogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApilogMaxAggregateInputType
}

export type GetApilogAggregateType<T extends ApilogAggregateArgs> = {
      [P in keyof T & keyof AggregateApilog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApilog[P]>
    : Prisma.GetScalarType<T[P], AggregateApilog[P]>
}




export type ApilogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApilogWhereInput
  orderBy?: Prisma.ApilogOrderByWithAggregationInput | Prisma.ApilogOrderByWithAggregationInput[]
  by: Prisma.ApilogScalarFieldEnum[] | Prisma.ApilogScalarFieldEnum
  having?: Prisma.ApilogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApilogCountAggregateInputType | true
  _avg?: ApilogAvgAggregateInputType
  _sum?: ApilogSumAggregateInputType
  _min?: ApilogMinAggregateInputType
  _max?: ApilogMaxAggregateInputType
}

export type ApilogGroupByOutputType = {
  id: bigint
  apiType: string
  methodName: string
  summary: string | null
  request: string | null
  response: string | null
  createdAt: Date | null
  _count: ApilogCountAggregateOutputType | null
  _avg: ApilogAvgAggregateOutputType | null
  _sum: ApilogSumAggregateOutputType | null
  _min: ApilogMinAggregateOutputType | null
  _max: ApilogMaxAggregateOutputType | null
}

type GetApilogGroupByPayload<T extends ApilogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApilogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApilogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApilogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApilogGroupByOutputType[P]>
      }
    >
  >



export type ApilogWhereInput = {
  AND?: Prisma.ApilogWhereInput | Prisma.ApilogWhereInput[]
  OR?: Prisma.ApilogWhereInput[]
  NOT?: Prisma.ApilogWhereInput | Prisma.ApilogWhereInput[]
  id?: Prisma.BigIntFilter<"Apilog"> | bigint | number
  apiType?: Prisma.StringFilter<"Apilog"> | string
  methodName?: Prisma.StringFilter<"Apilog"> | string
  summary?: Prisma.StringNullableFilter<"Apilog"> | string | null
  request?: Prisma.StringNullableFilter<"Apilog"> | string | null
  response?: Prisma.StringNullableFilter<"Apilog"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Apilog"> | Date | string | null
}

export type ApilogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  apiType?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  summary?: Prisma.SortOrderInput | Prisma.SortOrder
  request?: Prisma.SortOrderInput | Prisma.SortOrder
  response?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type ApilogWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.ApilogWhereInput | Prisma.ApilogWhereInput[]
  OR?: Prisma.ApilogWhereInput[]
  NOT?: Prisma.ApilogWhereInput | Prisma.ApilogWhereInput[]
  apiType?: Prisma.StringFilter<"Apilog"> | string
  methodName?: Prisma.StringFilter<"Apilog"> | string
  summary?: Prisma.StringNullableFilter<"Apilog"> | string | null
  request?: Prisma.StringNullableFilter<"Apilog"> | string | null
  response?: Prisma.StringNullableFilter<"Apilog"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Apilog"> | Date | string | null
}, "id">

export type ApilogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  apiType?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  summary?: Prisma.SortOrderInput | Prisma.SortOrder
  request?: Prisma.SortOrderInput | Prisma.SortOrder
  response?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ApilogCountOrderByAggregateInput
  _avg?: Prisma.ApilogAvgOrderByAggregateInput
  _max?: Prisma.ApilogMaxOrderByAggregateInput
  _min?: Prisma.ApilogMinOrderByAggregateInput
  _sum?: Prisma.ApilogSumOrderByAggregateInput
}

export type ApilogScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApilogScalarWhereWithAggregatesInput | Prisma.ApilogScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApilogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApilogScalarWhereWithAggregatesInput | Prisma.ApilogScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"Apilog"> | bigint | number
  apiType?: Prisma.StringWithAggregatesFilter<"Apilog"> | string
  methodName?: Prisma.StringWithAggregatesFilter<"Apilog"> | string
  summary?: Prisma.StringNullableWithAggregatesFilter<"Apilog"> | string | null
  request?: Prisma.StringNullableWithAggregatesFilter<"Apilog"> | string | null
  response?: Prisma.StringNullableWithAggregatesFilter<"Apilog"> | string | null
  createdAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Apilog"> | Date | string | null
}

export type ApilogCreateInput = {
  id?: bigint | number
  apiType: string
  methodName: string
  summary?: string | null
  request?: string | null
  response?: string | null
  createdAt?: Date | string | null
}

export type ApilogUncheckedCreateInput = {
  id?: bigint | number
  apiType: string
  methodName: string
  summary?: string | null
  request?: string | null
  response?: string | null
  createdAt?: Date | string | null
}

export type ApilogUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  apiType?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  request?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApilogUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  apiType?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  request?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApilogCreateManyInput = {
  id?: bigint | number
  apiType: string
  methodName: string
  summary?: string | null
  request?: string | null
  response?: string | null
  createdAt?: Date | string | null
}

export type ApilogUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  apiType?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  request?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApilogUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  apiType?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  request?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ApilogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiType?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  request?: Prisma.SortOrder
  response?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApilogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ApilogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiType?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  request?: Prisma.SortOrder
  response?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApilogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  apiType?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  request?: Prisma.SortOrder
  response?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApilogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type ApilogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiType?: boolean
  methodName?: boolean
  summary?: boolean
  request?: boolean
  response?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["apilog"]>

export type ApilogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiType?: boolean
  methodName?: boolean
  summary?: boolean
  request?: boolean
  response?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["apilog"]>

export type ApilogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  apiType?: boolean
  methodName?: boolean
  summary?: boolean
  request?: boolean
  response?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["apilog"]>

export type ApilogSelectScalar = {
  id?: boolean
  apiType?: boolean
  methodName?: boolean
  summary?: boolean
  request?: boolean
  response?: boolean
  createdAt?: boolean
}

export type ApilogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "apiType" | "methodName" | "summary" | "request" | "response" | "createdAt", ExtArgs["result"]["apilog"]>

export type $ApilogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Apilog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    apiType: string
    methodName: string
    summary: string | null
    request: string | null
    response: string | null
    createdAt: Date | null
  }, ExtArgs["result"]["apilog"]>
  composites: {}
}

export type ApilogGetPayload<S extends boolean | null | undefined | ApilogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApilogPayload, S>

export type ApilogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApilogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApilogCountAggregateInputType | true
  }

export interface ApilogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Apilog'], meta: { name: 'Apilog' } }
  /**
   * Find zero or one Apilog that matches the filter.
   * @param {ApilogFindUniqueArgs} args - Arguments to find a Apilog
   * @example
   * // Get one Apilog
   * const apilog = await prisma.apilog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApilogFindUniqueArgs>(args: Prisma.SelectSubset<T, ApilogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApilogClient<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Apilog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApilogFindUniqueOrThrowArgs} args - Arguments to find a Apilog
   * @example
   * // Get one Apilog
   * const apilog = await prisma.apilog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApilogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApilogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApilogClient<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Apilog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApilogFindFirstArgs} args - Arguments to find a Apilog
   * @example
   * // Get one Apilog
   * const apilog = await prisma.apilog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApilogFindFirstArgs>(args?: Prisma.SelectSubset<T, ApilogFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApilogClient<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Apilog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApilogFindFirstOrThrowArgs} args - Arguments to find a Apilog
   * @example
   * // Get one Apilog
   * const apilog = await prisma.apilog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApilogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApilogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApilogClient<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Apilogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApilogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Apilogs
   * const apilogs = await prisma.apilog.findMany()
   * 
   * // Get first 10 Apilogs
   * const apilogs = await prisma.apilog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const apilogWithIdOnly = await prisma.apilog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApilogFindManyArgs>(args?: Prisma.SelectSubset<T, ApilogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Apilog.
   * @param {ApilogCreateArgs} args - Arguments to create a Apilog.
   * @example
   * // Create one Apilog
   * const Apilog = await prisma.apilog.create({
   *   data: {
   *     // ... data to create a Apilog
   *   }
   * })
   * 
   */
  create<T extends ApilogCreateArgs>(args: Prisma.SelectSubset<T, ApilogCreateArgs<ExtArgs>>): Prisma.Prisma__ApilogClient<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Apilogs.
   * @param {ApilogCreateManyArgs} args - Arguments to create many Apilogs.
   * @example
   * // Create many Apilogs
   * const apilog = await prisma.apilog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApilogCreateManyArgs>(args?: Prisma.SelectSubset<T, ApilogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Apilogs and returns the data saved in the database.
   * @param {ApilogCreateManyAndReturnArgs} args - Arguments to create many Apilogs.
   * @example
   * // Create many Apilogs
   * const apilog = await prisma.apilog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Apilogs and only return the `id`
   * const apilogWithIdOnly = await prisma.apilog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApilogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApilogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Apilog.
   * @param {ApilogDeleteArgs} args - Arguments to delete one Apilog.
   * @example
   * // Delete one Apilog
   * const Apilog = await prisma.apilog.delete({
   *   where: {
   *     // ... filter to delete one Apilog
   *   }
   * })
   * 
   */
  delete<T extends ApilogDeleteArgs>(args: Prisma.SelectSubset<T, ApilogDeleteArgs<ExtArgs>>): Prisma.Prisma__ApilogClient<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Apilog.
   * @param {ApilogUpdateArgs} args - Arguments to update one Apilog.
   * @example
   * // Update one Apilog
   * const apilog = await prisma.apilog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApilogUpdateArgs>(args: Prisma.SelectSubset<T, ApilogUpdateArgs<ExtArgs>>): Prisma.Prisma__ApilogClient<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Apilogs.
   * @param {ApilogDeleteManyArgs} args - Arguments to filter Apilogs to delete.
   * @example
   * // Delete a few Apilogs
   * const { count } = await prisma.apilog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApilogDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApilogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Apilogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApilogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Apilogs
   * const apilog = await prisma.apilog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApilogUpdateManyArgs>(args: Prisma.SelectSubset<T, ApilogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Apilogs and returns the data updated in the database.
   * @param {ApilogUpdateManyAndReturnArgs} args - Arguments to update many Apilogs.
   * @example
   * // Update many Apilogs
   * const apilog = await prisma.apilog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Apilogs and only return the `id`
   * const apilogWithIdOnly = await prisma.apilog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApilogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApilogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Apilog.
   * @param {ApilogUpsertArgs} args - Arguments to update or create a Apilog.
   * @example
   * // Update or create a Apilog
   * const apilog = await prisma.apilog.upsert({
   *   create: {
   *     // ... data to create a Apilog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Apilog we want to update
   *   }
   * })
   */
  upsert<T extends ApilogUpsertArgs>(args: Prisma.SelectSubset<T, ApilogUpsertArgs<ExtArgs>>): Prisma.Prisma__ApilogClient<runtime.Types.Result.GetResult<Prisma.$ApilogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Apilogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApilogCountArgs} args - Arguments to filter Apilogs to count.
   * @example
   * // Count the number of Apilogs
   * const count = await prisma.apilog.count({
   *   where: {
   *     // ... the filter for the Apilogs we want to count
   *   }
   * })
  **/
  count<T extends ApilogCountArgs>(
    args?: Prisma.Subset<T, ApilogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApilogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Apilog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApilogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApilogAggregateArgs>(args: Prisma.Subset<T, ApilogAggregateArgs>): Prisma.PrismaPromise<GetApilogAggregateType<T>>

  /**
   * Group by Apilog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApilogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApilogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApilogGroupByArgs['orderBy'] }
      : { orderBy?: ApilogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApilogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApilogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Apilog model
 */
readonly fields: ApilogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Apilog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApilogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Apilog model
 */
export interface ApilogFieldRefs {
  readonly id: Prisma.FieldRef<"Apilog", 'BigInt'>
  readonly apiType: Prisma.FieldRef<"Apilog", 'String'>
  readonly methodName: Prisma.FieldRef<"Apilog", 'String'>
  readonly summary: Prisma.FieldRef<"Apilog", 'String'>
  readonly request: Prisma.FieldRef<"Apilog", 'String'>
  readonly response: Prisma.FieldRef<"Apilog", 'String'>
  readonly createdAt: Prisma.FieldRef<"Apilog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Apilog findUnique
 */
export type ApilogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * Filter, which Apilog to fetch.
   */
  where: Prisma.ApilogWhereUniqueInput
}

/**
 * Apilog findUniqueOrThrow
 */
export type ApilogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * Filter, which Apilog to fetch.
   */
  where: Prisma.ApilogWhereUniqueInput
}

/**
 * Apilog findFirst
 */
export type ApilogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * Filter, which Apilog to fetch.
   */
  where?: Prisma.ApilogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apilogs to fetch.
   */
  orderBy?: Prisma.ApilogOrderByWithRelationInput | Prisma.ApilogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Apilogs.
   */
  cursor?: Prisma.ApilogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apilogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apilogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Apilogs.
   */
  distinct?: Prisma.ApilogScalarFieldEnum | Prisma.ApilogScalarFieldEnum[]
}

/**
 * Apilog findFirstOrThrow
 */
export type ApilogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * Filter, which Apilog to fetch.
   */
  where?: Prisma.ApilogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apilogs to fetch.
   */
  orderBy?: Prisma.ApilogOrderByWithRelationInput | Prisma.ApilogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Apilogs.
   */
  cursor?: Prisma.ApilogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apilogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apilogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Apilogs.
   */
  distinct?: Prisma.ApilogScalarFieldEnum | Prisma.ApilogScalarFieldEnum[]
}

/**
 * Apilog findMany
 */
export type ApilogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * Filter, which Apilogs to fetch.
   */
  where?: Prisma.ApilogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apilogs to fetch.
   */
  orderBy?: Prisma.ApilogOrderByWithRelationInput | Prisma.ApilogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Apilogs.
   */
  cursor?: Prisma.ApilogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apilogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apilogs.
   */
  skip?: number
  distinct?: Prisma.ApilogScalarFieldEnum | Prisma.ApilogScalarFieldEnum[]
}

/**
 * Apilog create
 */
export type ApilogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * The data needed to create a Apilog.
   */
  data: Prisma.XOR<Prisma.ApilogCreateInput, Prisma.ApilogUncheckedCreateInput>
}

/**
 * Apilog createMany
 */
export type ApilogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Apilogs.
   */
  data: Prisma.ApilogCreateManyInput | Prisma.ApilogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Apilog createManyAndReturn
 */
export type ApilogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * The data used to create many Apilogs.
   */
  data: Prisma.ApilogCreateManyInput | Prisma.ApilogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Apilog update
 */
export type ApilogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * The data needed to update a Apilog.
   */
  data: Prisma.XOR<Prisma.ApilogUpdateInput, Prisma.ApilogUncheckedUpdateInput>
  /**
   * Choose, which Apilog to update.
   */
  where: Prisma.ApilogWhereUniqueInput
}

/**
 * Apilog updateMany
 */
export type ApilogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Apilogs.
   */
  data: Prisma.XOR<Prisma.ApilogUpdateManyMutationInput, Prisma.ApilogUncheckedUpdateManyInput>
  /**
   * Filter which Apilogs to update
   */
  where?: Prisma.ApilogWhereInput
  /**
   * Limit how many Apilogs to update.
   */
  limit?: number
}

/**
 * Apilog updateManyAndReturn
 */
export type ApilogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * The data used to update Apilogs.
   */
  data: Prisma.XOR<Prisma.ApilogUpdateManyMutationInput, Prisma.ApilogUncheckedUpdateManyInput>
  /**
   * Filter which Apilogs to update
   */
  where?: Prisma.ApilogWhereInput
  /**
   * Limit how many Apilogs to update.
   */
  limit?: number
}

/**
 * Apilog upsert
 */
export type ApilogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * The filter to search for the Apilog to update in case it exists.
   */
  where: Prisma.ApilogWhereUniqueInput
  /**
   * In case the Apilog found by the `where` argument doesn't exist, create a new Apilog with this data.
   */
  create: Prisma.XOR<Prisma.ApilogCreateInput, Prisma.ApilogUncheckedCreateInput>
  /**
   * In case the Apilog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApilogUpdateInput, Prisma.ApilogUncheckedUpdateInput>
}

/**
 * Apilog delete
 */
export type ApilogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
  /**
   * Filter which Apilog to delete.
   */
  where: Prisma.ApilogWhereUniqueInput
}

/**
 * Apilog deleteMany
 */
export type ApilogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Apilogs to delete
   */
  where?: Prisma.ApilogWhereInput
  /**
   * Limit how many Apilogs to delete.
   */
  limit?: number
}

/**
 * Apilog without action
 */
export type ApilogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Apilog
   */
  select?: Prisma.ApilogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Apilog
   */
  omit?: Prisma.ApilogOmit<ExtArgs> | null
}
