
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CreditAuditLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CreditAuditLog
 * 
 */
export type CreditAuditLogModel = runtime.Types.Result.DefaultSelection<Prisma.$CreditAuditLogPayload>

export type AggregateCreditAuditLog = {
  _count: CreditAuditLogCountAggregateOutputType | null
  _avg: CreditAuditLogAvgAggregateOutputType | null
  _sum: CreditAuditLogSumAggregateOutputType | null
  _min: CreditAuditLogMinAggregateOutputType | null
  _max: CreditAuditLogMaxAggregateOutputType | null
}

export type CreditAuditLogAvgAggregateOutputType = {
  id: number | null
  creditsChange: number | null
  deleted: number | null
}

export type CreditAuditLogSumAggregateOutputType = {
  id: bigint | null
  creditsChange: number | null
  deleted: number | null
}

export type CreditAuditLogMinAggregateOutputType = {
  id: bigint | null
  userId: string | null
  creditsChange: number | null
  feature: string | null
  creditType: string | null
  operationType: string | null
  operationReferId: string | null
  createdAt: Date | null
  deleted: number | null
}

export type CreditAuditLogMaxAggregateOutputType = {
  id: bigint | null
  userId: string | null
  creditsChange: number | null
  feature: string | null
  creditType: string | null
  operationType: string | null
  operationReferId: string | null
  createdAt: Date | null
  deleted: number | null
}

export type CreditAuditLogCountAggregateOutputType = {
  id: number
  userId: number
  creditsChange: number
  feature: number
  creditType: number
  operationType: number
  operationReferId: number
  createdAt: number
  deleted: number
  _all: number
}


export type CreditAuditLogAvgAggregateInputType = {
  id?: true
  creditsChange?: true
  deleted?: true
}

export type CreditAuditLogSumAggregateInputType = {
  id?: true
  creditsChange?: true
  deleted?: true
}

export type CreditAuditLogMinAggregateInputType = {
  id?: true
  userId?: true
  creditsChange?: true
  feature?: true
  creditType?: true
  operationType?: true
  operationReferId?: true
  createdAt?: true
  deleted?: true
}

export type CreditAuditLogMaxAggregateInputType = {
  id?: true
  userId?: true
  creditsChange?: true
  feature?: true
  creditType?: true
  operationType?: true
  operationReferId?: true
  createdAt?: true
  deleted?: true
}

export type CreditAuditLogCountAggregateInputType = {
  id?: true
  userId?: true
  creditsChange?: true
  feature?: true
  creditType?: true
  operationType?: true
  operationReferId?: true
  createdAt?: true
  deleted?: true
  _all?: true
}

export type CreditAuditLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CreditAuditLog to aggregate.
   */
  where?: Prisma.CreditAuditLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CreditAuditLogs to fetch.
   */
  orderBy?: Prisma.CreditAuditLogOrderByWithRelationInput | Prisma.CreditAuditLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CreditAuditLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CreditAuditLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CreditAuditLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CreditAuditLogs
  **/
  _count?: true | CreditAuditLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CreditAuditLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CreditAuditLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CreditAuditLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CreditAuditLogMaxAggregateInputType
}

export type GetCreditAuditLogAggregateType<T extends CreditAuditLogAggregateArgs> = {
      [P in keyof T & keyof AggregateCreditAuditLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCreditAuditLog[P]>
    : Prisma.GetScalarType<T[P], AggregateCreditAuditLog[P]>
}




export type CreditAuditLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CreditAuditLogWhereInput
  orderBy?: Prisma.CreditAuditLogOrderByWithAggregationInput | Prisma.CreditAuditLogOrderByWithAggregationInput[]
  by: Prisma.CreditAuditLogScalarFieldEnum[] | Prisma.CreditAuditLogScalarFieldEnum
  having?: Prisma.CreditAuditLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CreditAuditLogCountAggregateInputType | true
  _avg?: CreditAuditLogAvgAggregateInputType
  _sum?: CreditAuditLogSumAggregateInputType
  _min?: CreditAuditLogMinAggregateInputType
  _max?: CreditAuditLogMaxAggregateInputType
}

export type CreditAuditLogGroupByOutputType = {
  id: bigint
  userId: string
  creditsChange: number
  feature: string | null
  creditType: string
  operationType: string
  operationReferId: string | null
  createdAt: Date | null
  deleted: number
  _count: CreditAuditLogCountAggregateOutputType | null
  _avg: CreditAuditLogAvgAggregateOutputType | null
  _sum: CreditAuditLogSumAggregateOutputType | null
  _min: CreditAuditLogMinAggregateOutputType | null
  _max: CreditAuditLogMaxAggregateOutputType | null
}

type GetCreditAuditLogGroupByPayload<T extends CreditAuditLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CreditAuditLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CreditAuditLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CreditAuditLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CreditAuditLogGroupByOutputType[P]>
      }
    >
  >



export type CreditAuditLogWhereInput = {
  AND?: Prisma.CreditAuditLogWhereInput | Prisma.CreditAuditLogWhereInput[]
  OR?: Prisma.CreditAuditLogWhereInput[]
  NOT?: Prisma.CreditAuditLogWhereInput | Prisma.CreditAuditLogWhereInput[]
  id?: Prisma.BigIntFilter<"CreditAuditLog"> | bigint | number
  userId?: Prisma.UuidFilter<"CreditAuditLog"> | string
  creditsChange?: Prisma.IntFilter<"CreditAuditLog"> | number
  feature?: Prisma.StringNullableFilter<"CreditAuditLog"> | string | null
  creditType?: Prisma.StringFilter<"CreditAuditLog"> | string
  operationType?: Prisma.StringFilter<"CreditAuditLog"> | string
  operationReferId?: Prisma.StringNullableFilter<"CreditAuditLog"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"CreditAuditLog"> | Date | string | null
  deleted?: Prisma.IntFilter<"CreditAuditLog"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type CreditAuditLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  creditsChange?: Prisma.SortOrder
  feature?: Prisma.SortOrderInput | Prisma.SortOrder
  creditType?: Prisma.SortOrder
  operationType?: Prisma.SortOrder
  operationReferId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type CreditAuditLogWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.CreditAuditLogWhereInput | Prisma.CreditAuditLogWhereInput[]
  OR?: Prisma.CreditAuditLogWhereInput[]
  NOT?: Prisma.CreditAuditLogWhereInput | Prisma.CreditAuditLogWhereInput[]
  userId?: Prisma.UuidFilter<"CreditAuditLog"> | string
  creditsChange?: Prisma.IntFilter<"CreditAuditLog"> | number
  feature?: Prisma.StringNullableFilter<"CreditAuditLog"> | string | null
  creditType?: Prisma.StringFilter<"CreditAuditLog"> | string
  operationType?: Prisma.StringFilter<"CreditAuditLog"> | string
  operationReferId?: Prisma.StringNullableFilter<"CreditAuditLog"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"CreditAuditLog"> | Date | string | null
  deleted?: Prisma.IntFilter<"CreditAuditLog"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type CreditAuditLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  creditsChange?: Prisma.SortOrder
  feature?: Prisma.SortOrderInput | Prisma.SortOrder
  creditType?: Prisma.SortOrder
  operationType?: Prisma.SortOrder
  operationReferId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted?: Prisma.SortOrder
  _count?: Prisma.CreditAuditLogCountOrderByAggregateInput
  _avg?: Prisma.CreditAuditLogAvgOrderByAggregateInput
  _max?: Prisma.CreditAuditLogMaxOrderByAggregateInput
  _min?: Prisma.CreditAuditLogMinOrderByAggregateInput
  _sum?: Prisma.CreditAuditLogSumOrderByAggregateInput
}

export type CreditAuditLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.CreditAuditLogScalarWhereWithAggregatesInput | Prisma.CreditAuditLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.CreditAuditLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CreditAuditLogScalarWhereWithAggregatesInput | Prisma.CreditAuditLogScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"CreditAuditLog"> | bigint | number
  userId?: Prisma.UuidWithAggregatesFilter<"CreditAuditLog"> | string
  creditsChange?: Prisma.IntWithAggregatesFilter<"CreditAuditLog"> | number
  feature?: Prisma.StringNullableWithAggregatesFilter<"CreditAuditLog"> | string | null
  creditType?: Prisma.StringWithAggregatesFilter<"CreditAuditLog"> | string
  operationType?: Prisma.StringWithAggregatesFilter<"CreditAuditLog"> | string
  operationReferId?: Prisma.StringNullableWithAggregatesFilter<"CreditAuditLog"> | string | null
  createdAt?: Prisma.DateTimeNullableWithAggregatesFilter<"CreditAuditLog"> | Date | string | null
  deleted?: Prisma.IntWithAggregatesFilter<"CreditAuditLog"> | number
}

export type CreditAuditLogCreateInput = {
  id?: bigint | number
  creditsChange: number
  feature?: string | null
  creditType: string
  operationType: string
  operationReferId?: string | null
  createdAt?: Date | string | null
  deleted?: number
  user: Prisma.UserCreateNestedOneWithoutCreditAuditLogsInput
}

export type CreditAuditLogUncheckedCreateInput = {
  id?: bigint | number
  userId: string
  creditsChange: number
  feature?: string | null
  creditType: string
  operationType: string
  operationReferId?: string | null
  createdAt?: Date | string | null
  deleted?: number
}

export type CreditAuditLogUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  creditsChange?: Prisma.IntFieldUpdateOperationsInput | number
  feature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditType?: Prisma.StringFieldUpdateOperationsInput | string
  operationType?: Prisma.StringFieldUpdateOperationsInput | string
  operationReferId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutCreditAuditLogsNestedInput
}

export type CreditAuditLogUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  creditsChange?: Prisma.IntFieldUpdateOperationsInput | number
  feature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditType?: Prisma.StringFieldUpdateOperationsInput | string
  operationType?: Prisma.StringFieldUpdateOperationsInput | string
  operationReferId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CreditAuditLogCreateManyInput = {
  id?: bigint | number
  userId: string
  creditsChange: number
  feature?: string | null
  creditType: string
  operationType: string
  operationReferId?: string | null
  createdAt?: Date | string | null
  deleted?: number
}

export type CreditAuditLogUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  creditsChange?: Prisma.IntFieldUpdateOperationsInput | number
  feature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditType?: Prisma.StringFieldUpdateOperationsInput | string
  operationType?: Prisma.StringFieldUpdateOperationsInput | string
  operationReferId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CreditAuditLogUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  creditsChange?: Prisma.IntFieldUpdateOperationsInput | number
  feature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditType?: Prisma.StringFieldUpdateOperationsInput | string
  operationType?: Prisma.StringFieldUpdateOperationsInput | string
  operationReferId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CreditAuditLogListRelationFilter = {
  every?: Prisma.CreditAuditLogWhereInput
  some?: Prisma.CreditAuditLogWhereInput
  none?: Prisma.CreditAuditLogWhereInput
}

export type CreditAuditLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CreditAuditLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  creditsChange?: Prisma.SortOrder
  feature?: Prisma.SortOrder
  creditType?: Prisma.SortOrder
  operationType?: Prisma.SortOrder
  operationReferId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type CreditAuditLogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  creditsChange?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type CreditAuditLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  creditsChange?: Prisma.SortOrder
  feature?: Prisma.SortOrder
  creditType?: Prisma.SortOrder
  operationType?: Prisma.SortOrder
  operationReferId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type CreditAuditLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  creditsChange?: Prisma.SortOrder
  feature?: Prisma.SortOrder
  creditType?: Prisma.SortOrder
  operationType?: Prisma.SortOrder
  operationReferId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type CreditAuditLogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  creditsChange?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type CreditAuditLogCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CreditAuditLogCreateWithoutUserInput, Prisma.CreditAuditLogUncheckedCreateWithoutUserInput> | Prisma.CreditAuditLogCreateWithoutUserInput[] | Prisma.CreditAuditLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CreditAuditLogCreateOrConnectWithoutUserInput | Prisma.CreditAuditLogCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CreditAuditLogCreateManyUserInputEnvelope
  connect?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
}

export type CreditAuditLogUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CreditAuditLogCreateWithoutUserInput, Prisma.CreditAuditLogUncheckedCreateWithoutUserInput> | Prisma.CreditAuditLogCreateWithoutUserInput[] | Prisma.CreditAuditLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CreditAuditLogCreateOrConnectWithoutUserInput | Prisma.CreditAuditLogCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CreditAuditLogCreateManyUserInputEnvelope
  connect?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
}

export type CreditAuditLogUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CreditAuditLogCreateWithoutUserInput, Prisma.CreditAuditLogUncheckedCreateWithoutUserInput> | Prisma.CreditAuditLogCreateWithoutUserInput[] | Prisma.CreditAuditLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CreditAuditLogCreateOrConnectWithoutUserInput | Prisma.CreditAuditLogCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CreditAuditLogUpsertWithWhereUniqueWithoutUserInput | Prisma.CreditAuditLogUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CreditAuditLogCreateManyUserInputEnvelope
  set?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
  disconnect?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
  delete?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
  connect?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
  update?: Prisma.CreditAuditLogUpdateWithWhereUniqueWithoutUserInput | Prisma.CreditAuditLogUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CreditAuditLogUpdateManyWithWhereWithoutUserInput | Prisma.CreditAuditLogUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CreditAuditLogScalarWhereInput | Prisma.CreditAuditLogScalarWhereInput[]
}

export type CreditAuditLogUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CreditAuditLogCreateWithoutUserInput, Prisma.CreditAuditLogUncheckedCreateWithoutUserInput> | Prisma.CreditAuditLogCreateWithoutUserInput[] | Prisma.CreditAuditLogUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CreditAuditLogCreateOrConnectWithoutUserInput | Prisma.CreditAuditLogCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CreditAuditLogUpsertWithWhereUniqueWithoutUserInput | Prisma.CreditAuditLogUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CreditAuditLogCreateManyUserInputEnvelope
  set?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
  disconnect?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
  delete?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
  connect?: Prisma.CreditAuditLogWhereUniqueInput | Prisma.CreditAuditLogWhereUniqueInput[]
  update?: Prisma.CreditAuditLogUpdateWithWhereUniqueWithoutUserInput | Prisma.CreditAuditLogUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CreditAuditLogUpdateManyWithWhereWithoutUserInput | Prisma.CreditAuditLogUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CreditAuditLogScalarWhereInput | Prisma.CreditAuditLogScalarWhereInput[]
}

export type CreditAuditLogCreateWithoutUserInput = {
  id?: bigint | number
  creditsChange: number
  feature?: string | null
  creditType: string
  operationType: string
  operationReferId?: string | null
  createdAt?: Date | string | null
  deleted?: number
}

export type CreditAuditLogUncheckedCreateWithoutUserInput = {
  id?: bigint | number
  creditsChange: number
  feature?: string | null
  creditType: string
  operationType: string
  operationReferId?: string | null
  createdAt?: Date | string | null
  deleted?: number
}

export type CreditAuditLogCreateOrConnectWithoutUserInput = {
  where: Prisma.CreditAuditLogWhereUniqueInput
  create: Prisma.XOR<Prisma.CreditAuditLogCreateWithoutUserInput, Prisma.CreditAuditLogUncheckedCreateWithoutUserInput>
}

export type CreditAuditLogCreateManyUserInputEnvelope = {
  data: Prisma.CreditAuditLogCreateManyUserInput | Prisma.CreditAuditLogCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type CreditAuditLogUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CreditAuditLogWhereUniqueInput
  update: Prisma.XOR<Prisma.CreditAuditLogUpdateWithoutUserInput, Prisma.CreditAuditLogUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CreditAuditLogCreateWithoutUserInput, Prisma.CreditAuditLogUncheckedCreateWithoutUserInput>
}

export type CreditAuditLogUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CreditAuditLogWhereUniqueInput
  data: Prisma.XOR<Prisma.CreditAuditLogUpdateWithoutUserInput, Prisma.CreditAuditLogUncheckedUpdateWithoutUserInput>
}

export type CreditAuditLogUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CreditAuditLogScalarWhereInput
  data: Prisma.XOR<Prisma.CreditAuditLogUpdateManyMutationInput, Prisma.CreditAuditLogUncheckedUpdateManyWithoutUserInput>
}

export type CreditAuditLogScalarWhereInput = {
  AND?: Prisma.CreditAuditLogScalarWhereInput | Prisma.CreditAuditLogScalarWhereInput[]
  OR?: Prisma.CreditAuditLogScalarWhereInput[]
  NOT?: Prisma.CreditAuditLogScalarWhereInput | Prisma.CreditAuditLogScalarWhereInput[]
  id?: Prisma.BigIntFilter<"CreditAuditLog"> | bigint | number
  userId?: Prisma.UuidFilter<"CreditAuditLog"> | string
  creditsChange?: Prisma.IntFilter<"CreditAuditLog"> | number
  feature?: Prisma.StringNullableFilter<"CreditAuditLog"> | string | null
  creditType?: Prisma.StringFilter<"CreditAuditLog"> | string
  operationType?: Prisma.StringFilter<"CreditAuditLog"> | string
  operationReferId?: Prisma.StringNullableFilter<"CreditAuditLog"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"CreditAuditLog"> | Date | string | null
  deleted?: Prisma.IntFilter<"CreditAuditLog"> | number
}

export type CreditAuditLogCreateManyUserInput = {
  id?: bigint | number
  creditsChange: number
  feature?: string | null
  creditType: string
  operationType: string
  operationReferId?: string | null
  createdAt?: Date | string | null
  deleted?: number
}

export type CreditAuditLogUpdateWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  creditsChange?: Prisma.IntFieldUpdateOperationsInput | number
  feature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditType?: Prisma.StringFieldUpdateOperationsInput | string
  operationType?: Prisma.StringFieldUpdateOperationsInput | string
  operationReferId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CreditAuditLogUncheckedUpdateWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  creditsChange?: Prisma.IntFieldUpdateOperationsInput | number
  feature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditType?: Prisma.StringFieldUpdateOperationsInput | string
  operationType?: Prisma.StringFieldUpdateOperationsInput | string
  operationReferId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CreditAuditLogUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  creditsChange?: Prisma.IntFieldUpdateOperationsInput | number
  feature?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creditType?: Prisma.StringFieldUpdateOperationsInput | string
  operationType?: Prisma.StringFieldUpdateOperationsInput | string
  operationReferId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}



export type CreditAuditLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  creditsChange?: boolean
  feature?: boolean
  creditType?: boolean
  operationType?: boolean
  operationReferId?: boolean
  createdAt?: boolean
  deleted?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["creditAuditLog"]>

export type CreditAuditLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  creditsChange?: boolean
  feature?: boolean
  creditType?: boolean
  operationType?: boolean
  operationReferId?: boolean
  createdAt?: boolean
  deleted?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["creditAuditLog"]>

export type CreditAuditLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  creditsChange?: boolean
  feature?: boolean
  creditType?: boolean
  operationType?: boolean
  operationReferId?: boolean
  createdAt?: boolean
  deleted?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["creditAuditLog"]>

export type CreditAuditLogSelectScalar = {
  id?: boolean
  userId?: boolean
  creditsChange?: boolean
  feature?: boolean
  creditType?: boolean
  operationType?: boolean
  operationReferId?: boolean
  createdAt?: boolean
  deleted?: boolean
}

export type CreditAuditLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "creditsChange" | "feature" | "creditType" | "operationType" | "operationReferId" | "createdAt" | "deleted", ExtArgs["result"]["creditAuditLog"]>
export type CreditAuditLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CreditAuditLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CreditAuditLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CreditAuditLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CreditAuditLog"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    userId: string
    creditsChange: number
    feature: string | null
    creditType: string
    operationType: string
    operationReferId: string | null
    createdAt: Date | null
    deleted: number
  }, ExtArgs["result"]["creditAuditLog"]>
  composites: {}
}

export type CreditAuditLogGetPayload<S extends boolean | null | undefined | CreditAuditLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload, S>

export type CreditAuditLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CreditAuditLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CreditAuditLogCountAggregateInputType | true
  }

export interface CreditAuditLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CreditAuditLog'], meta: { name: 'CreditAuditLog' } }
  /**
   * Find zero or one CreditAuditLog that matches the filter.
   * @param {CreditAuditLogFindUniqueArgs} args - Arguments to find a CreditAuditLog
   * @example
   * // Get one CreditAuditLog
   * const creditAuditLog = await prisma.creditAuditLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CreditAuditLogFindUniqueArgs>(args: Prisma.SelectSubset<T, CreditAuditLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CreditAuditLogClient<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CreditAuditLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CreditAuditLogFindUniqueOrThrowArgs} args - Arguments to find a CreditAuditLog
   * @example
   * // Get one CreditAuditLog
   * const creditAuditLog = await prisma.creditAuditLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CreditAuditLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CreditAuditLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CreditAuditLogClient<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CreditAuditLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CreditAuditLogFindFirstArgs} args - Arguments to find a CreditAuditLog
   * @example
   * // Get one CreditAuditLog
   * const creditAuditLog = await prisma.creditAuditLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CreditAuditLogFindFirstArgs>(args?: Prisma.SelectSubset<T, CreditAuditLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__CreditAuditLogClient<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CreditAuditLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CreditAuditLogFindFirstOrThrowArgs} args - Arguments to find a CreditAuditLog
   * @example
   * // Get one CreditAuditLog
   * const creditAuditLog = await prisma.creditAuditLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CreditAuditLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CreditAuditLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CreditAuditLogClient<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CreditAuditLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CreditAuditLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CreditAuditLogs
   * const creditAuditLogs = await prisma.creditAuditLog.findMany()
   * 
   * // Get first 10 CreditAuditLogs
   * const creditAuditLogs = await prisma.creditAuditLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const creditAuditLogWithIdOnly = await prisma.creditAuditLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CreditAuditLogFindManyArgs>(args?: Prisma.SelectSubset<T, CreditAuditLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CreditAuditLog.
   * @param {CreditAuditLogCreateArgs} args - Arguments to create a CreditAuditLog.
   * @example
   * // Create one CreditAuditLog
   * const CreditAuditLog = await prisma.creditAuditLog.create({
   *   data: {
   *     // ... data to create a CreditAuditLog
   *   }
   * })
   * 
   */
  create<T extends CreditAuditLogCreateArgs>(args: Prisma.SelectSubset<T, CreditAuditLogCreateArgs<ExtArgs>>): Prisma.Prisma__CreditAuditLogClient<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CreditAuditLogs.
   * @param {CreditAuditLogCreateManyArgs} args - Arguments to create many CreditAuditLogs.
   * @example
   * // Create many CreditAuditLogs
   * const creditAuditLog = await prisma.creditAuditLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CreditAuditLogCreateManyArgs>(args?: Prisma.SelectSubset<T, CreditAuditLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CreditAuditLogs and returns the data saved in the database.
   * @param {CreditAuditLogCreateManyAndReturnArgs} args - Arguments to create many CreditAuditLogs.
   * @example
   * // Create many CreditAuditLogs
   * const creditAuditLog = await prisma.creditAuditLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CreditAuditLogs and only return the `id`
   * const creditAuditLogWithIdOnly = await prisma.creditAuditLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CreditAuditLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CreditAuditLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CreditAuditLog.
   * @param {CreditAuditLogDeleteArgs} args - Arguments to delete one CreditAuditLog.
   * @example
   * // Delete one CreditAuditLog
   * const CreditAuditLog = await prisma.creditAuditLog.delete({
   *   where: {
   *     // ... filter to delete one CreditAuditLog
   *   }
   * })
   * 
   */
  delete<T extends CreditAuditLogDeleteArgs>(args: Prisma.SelectSubset<T, CreditAuditLogDeleteArgs<ExtArgs>>): Prisma.Prisma__CreditAuditLogClient<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CreditAuditLog.
   * @param {CreditAuditLogUpdateArgs} args - Arguments to update one CreditAuditLog.
   * @example
   * // Update one CreditAuditLog
   * const creditAuditLog = await prisma.creditAuditLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CreditAuditLogUpdateArgs>(args: Prisma.SelectSubset<T, CreditAuditLogUpdateArgs<ExtArgs>>): Prisma.Prisma__CreditAuditLogClient<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CreditAuditLogs.
   * @param {CreditAuditLogDeleteManyArgs} args - Arguments to filter CreditAuditLogs to delete.
   * @example
   * // Delete a few CreditAuditLogs
   * const { count } = await prisma.creditAuditLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CreditAuditLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, CreditAuditLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CreditAuditLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CreditAuditLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CreditAuditLogs
   * const creditAuditLog = await prisma.creditAuditLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CreditAuditLogUpdateManyArgs>(args: Prisma.SelectSubset<T, CreditAuditLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CreditAuditLogs and returns the data updated in the database.
   * @param {CreditAuditLogUpdateManyAndReturnArgs} args - Arguments to update many CreditAuditLogs.
   * @example
   * // Update many CreditAuditLogs
   * const creditAuditLog = await prisma.creditAuditLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CreditAuditLogs and only return the `id`
   * const creditAuditLogWithIdOnly = await prisma.creditAuditLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CreditAuditLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CreditAuditLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CreditAuditLog.
   * @param {CreditAuditLogUpsertArgs} args - Arguments to update or create a CreditAuditLog.
   * @example
   * // Update or create a CreditAuditLog
   * const creditAuditLog = await prisma.creditAuditLog.upsert({
   *   create: {
   *     // ... data to create a CreditAuditLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CreditAuditLog we want to update
   *   }
   * })
   */
  upsert<T extends CreditAuditLogUpsertArgs>(args: Prisma.SelectSubset<T, CreditAuditLogUpsertArgs<ExtArgs>>): Prisma.Prisma__CreditAuditLogClient<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CreditAuditLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CreditAuditLogCountArgs} args - Arguments to filter CreditAuditLogs to count.
   * @example
   * // Count the number of CreditAuditLogs
   * const count = await prisma.creditAuditLog.count({
   *   where: {
   *     // ... the filter for the CreditAuditLogs we want to count
   *   }
   * })
  **/
  count<T extends CreditAuditLogCountArgs>(
    args?: Prisma.Subset<T, CreditAuditLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CreditAuditLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CreditAuditLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CreditAuditLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CreditAuditLogAggregateArgs>(args: Prisma.Subset<T, CreditAuditLogAggregateArgs>): Prisma.PrismaPromise<GetCreditAuditLogAggregateType<T>>

  /**
   * Group by CreditAuditLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CreditAuditLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CreditAuditLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CreditAuditLogGroupByArgs['orderBy'] }
      : { orderBy?: CreditAuditLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CreditAuditLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCreditAuditLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CreditAuditLog model
 */
readonly fields: CreditAuditLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CreditAuditLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CreditAuditLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CreditAuditLog model
 */
export interface CreditAuditLogFieldRefs {
  readonly id: Prisma.FieldRef<"CreditAuditLog", 'BigInt'>
  readonly userId: Prisma.FieldRef<"CreditAuditLog", 'String'>
  readonly creditsChange: Prisma.FieldRef<"CreditAuditLog", 'Int'>
  readonly feature: Prisma.FieldRef<"CreditAuditLog", 'String'>
  readonly creditType: Prisma.FieldRef<"CreditAuditLog", 'String'>
  readonly operationType: Prisma.FieldRef<"CreditAuditLog", 'String'>
  readonly operationReferId: Prisma.FieldRef<"CreditAuditLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"CreditAuditLog", 'DateTime'>
  readonly deleted: Prisma.FieldRef<"CreditAuditLog", 'Int'>
}
    

// Custom InputTypes
/**
 * CreditAuditLog findUnique
 */
export type CreditAuditLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * Filter, which CreditAuditLog to fetch.
   */
  where: Prisma.CreditAuditLogWhereUniqueInput
}

/**
 * CreditAuditLog findUniqueOrThrow
 */
export type CreditAuditLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * Filter, which CreditAuditLog to fetch.
   */
  where: Prisma.CreditAuditLogWhereUniqueInput
}

/**
 * CreditAuditLog findFirst
 */
export type CreditAuditLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * Filter, which CreditAuditLog to fetch.
   */
  where?: Prisma.CreditAuditLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CreditAuditLogs to fetch.
   */
  orderBy?: Prisma.CreditAuditLogOrderByWithRelationInput | Prisma.CreditAuditLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CreditAuditLogs.
   */
  cursor?: Prisma.CreditAuditLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CreditAuditLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CreditAuditLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CreditAuditLogs.
   */
  distinct?: Prisma.CreditAuditLogScalarFieldEnum | Prisma.CreditAuditLogScalarFieldEnum[]
}

/**
 * CreditAuditLog findFirstOrThrow
 */
export type CreditAuditLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * Filter, which CreditAuditLog to fetch.
   */
  where?: Prisma.CreditAuditLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CreditAuditLogs to fetch.
   */
  orderBy?: Prisma.CreditAuditLogOrderByWithRelationInput | Prisma.CreditAuditLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CreditAuditLogs.
   */
  cursor?: Prisma.CreditAuditLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CreditAuditLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CreditAuditLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CreditAuditLogs.
   */
  distinct?: Prisma.CreditAuditLogScalarFieldEnum | Prisma.CreditAuditLogScalarFieldEnum[]
}

/**
 * CreditAuditLog findMany
 */
export type CreditAuditLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * Filter, which CreditAuditLogs to fetch.
   */
  where?: Prisma.CreditAuditLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CreditAuditLogs to fetch.
   */
  orderBy?: Prisma.CreditAuditLogOrderByWithRelationInput | Prisma.CreditAuditLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CreditAuditLogs.
   */
  cursor?: Prisma.CreditAuditLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CreditAuditLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CreditAuditLogs.
   */
  skip?: number
  distinct?: Prisma.CreditAuditLogScalarFieldEnum | Prisma.CreditAuditLogScalarFieldEnum[]
}

/**
 * CreditAuditLog create
 */
export type CreditAuditLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * The data needed to create a CreditAuditLog.
   */
  data: Prisma.XOR<Prisma.CreditAuditLogCreateInput, Prisma.CreditAuditLogUncheckedCreateInput>
}

/**
 * CreditAuditLog createMany
 */
export type CreditAuditLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CreditAuditLogs.
   */
  data: Prisma.CreditAuditLogCreateManyInput | Prisma.CreditAuditLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CreditAuditLog createManyAndReturn
 */
export type CreditAuditLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * The data used to create many CreditAuditLogs.
   */
  data: Prisma.CreditAuditLogCreateManyInput | Prisma.CreditAuditLogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CreditAuditLog update
 */
export type CreditAuditLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * The data needed to update a CreditAuditLog.
   */
  data: Prisma.XOR<Prisma.CreditAuditLogUpdateInput, Prisma.CreditAuditLogUncheckedUpdateInput>
  /**
   * Choose, which CreditAuditLog to update.
   */
  where: Prisma.CreditAuditLogWhereUniqueInput
}

/**
 * CreditAuditLog updateMany
 */
export type CreditAuditLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CreditAuditLogs.
   */
  data: Prisma.XOR<Prisma.CreditAuditLogUpdateManyMutationInput, Prisma.CreditAuditLogUncheckedUpdateManyInput>
  /**
   * Filter which CreditAuditLogs to update
   */
  where?: Prisma.CreditAuditLogWhereInput
  /**
   * Limit how many CreditAuditLogs to update.
   */
  limit?: number
}

/**
 * CreditAuditLog updateManyAndReturn
 */
export type CreditAuditLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * The data used to update CreditAuditLogs.
   */
  data: Prisma.XOR<Prisma.CreditAuditLogUpdateManyMutationInput, Prisma.CreditAuditLogUncheckedUpdateManyInput>
  /**
   * Filter which CreditAuditLogs to update
   */
  where?: Prisma.CreditAuditLogWhereInput
  /**
   * Limit how many CreditAuditLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CreditAuditLog upsert
 */
export type CreditAuditLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * The filter to search for the CreditAuditLog to update in case it exists.
   */
  where: Prisma.CreditAuditLogWhereUniqueInput
  /**
   * In case the CreditAuditLog found by the `where` argument doesn't exist, create a new CreditAuditLog with this data.
   */
  create: Prisma.XOR<Prisma.CreditAuditLogCreateInput, Prisma.CreditAuditLogUncheckedCreateInput>
  /**
   * In case the CreditAuditLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CreditAuditLogUpdateInput, Prisma.CreditAuditLogUncheckedUpdateInput>
}

/**
 * CreditAuditLog delete
 */
export type CreditAuditLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  /**
   * Filter which CreditAuditLog to delete.
   */
  where: Prisma.CreditAuditLogWhereUniqueInput
}

/**
 * CreditAuditLog deleteMany
 */
export type CreditAuditLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CreditAuditLogs to delete
   */
  where?: Prisma.CreditAuditLogWhereInput
  /**
   * Limit how many CreditAuditLogs to delete.
   */
  limit?: number
}

/**
 * CreditAuditLog without action
 */
export type CreditAuditLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
}
