
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserBackup` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserBackup
 * 
 */
export type UserBackupModel = runtime.Types.Result.DefaultSelection<Prisma.$UserBackupPayload>

export type AggregateUserBackup = {
  _count: UserBackupCountAggregateOutputType | null
  _avg: UserBackupAvgAggregateOutputType | null
  _sum: UserBackupSumAggregateOutputType | null
  _min: UserBackupMinAggregateOutputType | null
  _max: UserBackupMaxAggregateOutputType | null
}

export type UserBackupAvgAggregateOutputType = {
  id: number | null
  deleted: number | null
}

export type UserBackupSumAggregateOutputType = {
  id: bigint | null
  deleted: number | null
}

export type UserBackupMinAggregateOutputType = {
  id: bigint | null
  originalUserId: string | null
  status: string | null
  fingerprintId: string | null
  clerkUserId: string | null
  stripeCusId: string | null
  email: string | null
  userName: string | null
  deletedAt: Date | null
  createdAt: Date | null
  deleted: number | null
}

export type UserBackupMaxAggregateOutputType = {
  id: bigint | null
  originalUserId: string | null
  status: string | null
  fingerprintId: string | null
  clerkUserId: string | null
  stripeCusId: string | null
  email: string | null
  userName: string | null
  deletedAt: Date | null
  createdAt: Date | null
  deleted: number | null
}

export type UserBackupCountAggregateOutputType = {
  id: number
  originalUserId: number
  status: number
  fingerprintId: number
  clerkUserId: number
  stripeCusId: number
  email: number
  userName: number
  backupData: number
  deletedAt: number
  createdAt: number
  deleted: number
  _all: number
}


export type UserBackupAvgAggregateInputType = {
  id?: true
  deleted?: true
}

export type UserBackupSumAggregateInputType = {
  id?: true
  deleted?: true
}

export type UserBackupMinAggregateInputType = {
  id?: true
  originalUserId?: true
  status?: true
  fingerprintId?: true
  clerkUserId?: true
  stripeCusId?: true
  email?: true
  userName?: true
  deletedAt?: true
  createdAt?: true
  deleted?: true
}

export type UserBackupMaxAggregateInputType = {
  id?: true
  originalUserId?: true
  status?: true
  fingerprintId?: true
  clerkUserId?: true
  stripeCusId?: true
  email?: true
  userName?: true
  deletedAt?: true
  createdAt?: true
  deleted?: true
}

export type UserBackupCountAggregateInputType = {
  id?: true
  originalUserId?: true
  status?: true
  fingerprintId?: true
  clerkUserId?: true
  stripeCusId?: true
  email?: true
  userName?: true
  backupData?: true
  deletedAt?: true
  createdAt?: true
  deleted?: true
  _all?: true
}

export type UserBackupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBackup to aggregate.
   */
  where?: Prisma.UserBackupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBackups to fetch.
   */
  orderBy?: Prisma.UserBackupOrderByWithRelationInput | Prisma.UserBackupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserBackupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBackups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBackups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserBackups
  **/
  _count?: true | UserBackupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserBackupAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserBackupSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserBackupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserBackupMaxAggregateInputType
}

export type GetUserBackupAggregateType<T extends UserBackupAggregateArgs> = {
      [P in keyof T & keyof AggregateUserBackup]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserBackup[P]>
    : Prisma.GetScalarType<T[P], AggregateUserBackup[P]>
}




export type UserBackupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserBackupWhereInput
  orderBy?: Prisma.UserBackupOrderByWithAggregationInput | Prisma.UserBackupOrderByWithAggregationInput[]
  by: Prisma.UserBackupScalarFieldEnum[] | Prisma.UserBackupScalarFieldEnum
  having?: Prisma.UserBackupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserBackupCountAggregateInputType | true
  _avg?: UserBackupAvgAggregateInputType
  _sum?: UserBackupSumAggregateInputType
  _min?: UserBackupMinAggregateInputType
  _max?: UserBackupMaxAggregateInputType
}

export type UserBackupGroupByOutputType = {
  id: bigint
  originalUserId: string
  status: string | null
  fingerprintId: string | null
  clerkUserId: string | null
  stripeCusId: string | null
  email: string | null
  userName: string | null
  backupData: runtime.JsonValue | null
  deletedAt: Date | null
  createdAt: Date | null
  deleted: number
  _count: UserBackupCountAggregateOutputType | null
  _avg: UserBackupAvgAggregateOutputType | null
  _sum: UserBackupSumAggregateOutputType | null
  _min: UserBackupMinAggregateOutputType | null
  _max: UserBackupMaxAggregateOutputType | null
}

type GetUserBackupGroupByPayload<T extends UserBackupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserBackupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserBackupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserBackupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserBackupGroupByOutputType[P]>
      }
    >
  >



export type UserBackupWhereInput = {
  AND?: Prisma.UserBackupWhereInput | Prisma.UserBackupWhereInput[]
  OR?: Prisma.UserBackupWhereInput[]
  NOT?: Prisma.UserBackupWhereInput | Prisma.UserBackupWhereInput[]
  id?: Prisma.BigIntFilter<"UserBackup"> | bigint | number
  originalUserId?: Prisma.UuidFilter<"UserBackup"> | string
  status?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  fingerprintId?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  clerkUserId?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  stripeCusId?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  email?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  userName?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  backupData?: Prisma.JsonNullableFilter<"UserBackup">
  deletedAt?: Prisma.DateTimeNullableFilter<"UserBackup"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"UserBackup"> | Date | string | null
  deleted?: Prisma.IntFilter<"UserBackup"> | number
}

export type UserBackupOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  originalUserId?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  fingerprintId?: Prisma.SortOrderInput | Prisma.SortOrder
  clerkUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeCusId?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  userName?: Prisma.SortOrderInput | Prisma.SortOrder
  backupData?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type UserBackupWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.UserBackupWhereInput | Prisma.UserBackupWhereInput[]
  OR?: Prisma.UserBackupWhereInput[]
  NOT?: Prisma.UserBackupWhereInput | Prisma.UserBackupWhereInput[]
  originalUserId?: Prisma.UuidFilter<"UserBackup"> | string
  status?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  fingerprintId?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  clerkUserId?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  stripeCusId?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  email?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  userName?: Prisma.StringNullableFilter<"UserBackup"> | string | null
  backupData?: Prisma.JsonNullableFilter<"UserBackup">
  deletedAt?: Prisma.DateTimeNullableFilter<"UserBackup"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"UserBackup"> | Date | string | null
  deleted?: Prisma.IntFilter<"UserBackup"> | number
}, "id">

export type UserBackupOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  originalUserId?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  fingerprintId?: Prisma.SortOrderInput | Prisma.SortOrder
  clerkUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeCusId?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  userName?: Prisma.SortOrderInput | Prisma.SortOrder
  backupData?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted?: Prisma.SortOrder
  _count?: Prisma.UserBackupCountOrderByAggregateInput
  _avg?: Prisma.UserBackupAvgOrderByAggregateInput
  _max?: Prisma.UserBackupMaxOrderByAggregateInput
  _min?: Prisma.UserBackupMinOrderByAggregateInput
  _sum?: Prisma.UserBackupSumOrderByAggregateInput
}

export type UserBackupScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserBackupScalarWhereWithAggregatesInput | Prisma.UserBackupScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserBackupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserBackupScalarWhereWithAggregatesInput | Prisma.UserBackupScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"UserBackup"> | bigint | number
  originalUserId?: Prisma.UuidWithAggregatesFilter<"UserBackup"> | string
  status?: Prisma.StringNullableWithAggregatesFilter<"UserBackup"> | string | null
  fingerprintId?: Prisma.StringNullableWithAggregatesFilter<"UserBackup"> | string | null
  clerkUserId?: Prisma.StringNullableWithAggregatesFilter<"UserBackup"> | string | null
  stripeCusId?: Prisma.StringNullableWithAggregatesFilter<"UserBackup"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"UserBackup"> | string | null
  userName?: Prisma.StringNullableWithAggregatesFilter<"UserBackup"> | string | null
  backupData?: Prisma.JsonNullableWithAggregatesFilter<"UserBackup">
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"UserBackup"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableWithAggregatesFilter<"UserBackup"> | Date | string | null
  deleted?: Prisma.IntWithAggregatesFilter<"UserBackup"> | number
}

export type UserBackupCreateInput = {
  id?: bigint | number
  originalUserId: string
  status?: string | null
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  backupData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  deletedAt?: Date | string | null
  createdAt?: Date | string | null
  deleted?: number
}

export type UserBackupUncheckedCreateInput = {
  id?: bigint | number
  originalUserId: string
  status?: string | null
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  backupData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  deletedAt?: Date | string | null
  createdAt?: Date | string | null
  deleted?: number
}

export type UserBackupUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  originalUserId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backupData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBackupUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  originalUserId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backupData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBackupCreateManyInput = {
  id?: bigint | number
  originalUserId: string
  status?: string | null
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  backupData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  deletedAt?: Date | string | null
  createdAt?: Date | string | null
  deleted?: number
}

export type UserBackupUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  originalUserId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backupData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBackupUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  originalUserId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  backupData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deleted?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBackupCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  originalUserId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fingerprintId?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  stripeCusId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  backupData?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type UserBackupAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type UserBackupMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  originalUserId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fingerprintId?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  stripeCusId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type UserBackupMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  originalUserId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fingerprintId?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  stripeCusId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}

export type UserBackupSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
}



export type UserBackupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  originalUserId?: boolean
  status?: boolean
  fingerprintId?: boolean
  clerkUserId?: boolean
  stripeCusId?: boolean
  email?: boolean
  userName?: boolean
  backupData?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  deleted?: boolean
}, ExtArgs["result"]["userBackup"]>

export type UserBackupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  originalUserId?: boolean
  status?: boolean
  fingerprintId?: boolean
  clerkUserId?: boolean
  stripeCusId?: boolean
  email?: boolean
  userName?: boolean
  backupData?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  deleted?: boolean
}, ExtArgs["result"]["userBackup"]>

export type UserBackupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  originalUserId?: boolean
  status?: boolean
  fingerprintId?: boolean
  clerkUserId?: boolean
  stripeCusId?: boolean
  email?: boolean
  userName?: boolean
  backupData?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  deleted?: boolean
}, ExtArgs["result"]["userBackup"]>

export type UserBackupSelectScalar = {
  id?: boolean
  originalUserId?: boolean
  status?: boolean
  fingerprintId?: boolean
  clerkUserId?: boolean
  stripeCusId?: boolean
  email?: boolean
  userName?: boolean
  backupData?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  deleted?: boolean
}

export type UserBackupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "originalUserId" | "status" | "fingerprintId" | "clerkUserId" | "stripeCusId" | "email" | "userName" | "backupData" | "deletedAt" | "createdAt" | "deleted", ExtArgs["result"]["userBackup"]>

export type $UserBackupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserBackup"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    originalUserId: string
    status: string | null
    fingerprintId: string | null
    clerkUserId: string | null
    stripeCusId: string | null
    email: string | null
    userName: string | null
    backupData: runtime.JsonValue | null
    deletedAt: Date | null
    createdAt: Date | null
    deleted: number
  }, ExtArgs["result"]["userBackup"]>
  composites: {}
}

export type UserBackupGetPayload<S extends boolean | null | undefined | UserBackupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserBackupPayload, S>

export type UserBackupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserBackupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserBackupCountAggregateInputType | true
  }

export interface UserBackupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserBackup'], meta: { name: 'UserBackup' } }
  /**
   * Find zero or one UserBackup that matches the filter.
   * @param {UserBackupFindUniqueArgs} args - Arguments to find a UserBackup
   * @example
   * // Get one UserBackup
   * const userBackup = await prisma.userBackup.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserBackupFindUniqueArgs>(args: Prisma.SelectSubset<T, UserBackupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserBackupClient<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserBackup that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserBackupFindUniqueOrThrowArgs} args - Arguments to find a UserBackup
   * @example
   * // Get one UserBackup
   * const userBackup = await prisma.userBackup.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserBackupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserBackupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBackupClient<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBackup that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBackupFindFirstArgs} args - Arguments to find a UserBackup
   * @example
   * // Get one UserBackup
   * const userBackup = await prisma.userBackup.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserBackupFindFirstArgs>(args?: Prisma.SelectSubset<T, UserBackupFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserBackupClient<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBackup that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBackupFindFirstOrThrowArgs} args - Arguments to find a UserBackup
   * @example
   * // Get one UserBackup
   * const userBackup = await prisma.userBackup.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserBackupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserBackupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBackupClient<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserBackups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBackupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserBackups
   * const userBackups = await prisma.userBackup.findMany()
   * 
   * // Get first 10 UserBackups
   * const userBackups = await prisma.userBackup.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userBackupWithIdOnly = await prisma.userBackup.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserBackupFindManyArgs>(args?: Prisma.SelectSubset<T, UserBackupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserBackup.
   * @param {UserBackupCreateArgs} args - Arguments to create a UserBackup.
   * @example
   * // Create one UserBackup
   * const UserBackup = await prisma.userBackup.create({
   *   data: {
   *     // ... data to create a UserBackup
   *   }
   * })
   * 
   */
  create<T extends UserBackupCreateArgs>(args: Prisma.SelectSubset<T, UserBackupCreateArgs<ExtArgs>>): Prisma.Prisma__UserBackupClient<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserBackups.
   * @param {UserBackupCreateManyArgs} args - Arguments to create many UserBackups.
   * @example
   * // Create many UserBackups
   * const userBackup = await prisma.userBackup.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserBackupCreateManyArgs>(args?: Prisma.SelectSubset<T, UserBackupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserBackups and returns the data saved in the database.
   * @param {UserBackupCreateManyAndReturnArgs} args - Arguments to create many UserBackups.
   * @example
   * // Create many UserBackups
   * const userBackup = await prisma.userBackup.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserBackups and only return the `id`
   * const userBackupWithIdOnly = await prisma.userBackup.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserBackupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserBackupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserBackup.
   * @param {UserBackupDeleteArgs} args - Arguments to delete one UserBackup.
   * @example
   * // Delete one UserBackup
   * const UserBackup = await prisma.userBackup.delete({
   *   where: {
   *     // ... filter to delete one UserBackup
   *   }
   * })
   * 
   */
  delete<T extends UserBackupDeleteArgs>(args: Prisma.SelectSubset<T, UserBackupDeleteArgs<ExtArgs>>): Prisma.Prisma__UserBackupClient<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserBackup.
   * @param {UserBackupUpdateArgs} args - Arguments to update one UserBackup.
   * @example
   * // Update one UserBackup
   * const userBackup = await prisma.userBackup.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserBackupUpdateArgs>(args: Prisma.SelectSubset<T, UserBackupUpdateArgs<ExtArgs>>): Prisma.Prisma__UserBackupClient<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserBackups.
   * @param {UserBackupDeleteManyArgs} args - Arguments to filter UserBackups to delete.
   * @example
   * // Delete a few UserBackups
   * const { count } = await prisma.userBackup.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserBackupDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserBackupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBackups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBackupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserBackups
   * const userBackup = await prisma.userBackup.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserBackupUpdateManyArgs>(args: Prisma.SelectSubset<T, UserBackupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBackups and returns the data updated in the database.
   * @param {UserBackupUpdateManyAndReturnArgs} args - Arguments to update many UserBackups.
   * @example
   * // Update many UserBackups
   * const userBackup = await prisma.userBackup.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserBackups and only return the `id`
   * const userBackupWithIdOnly = await prisma.userBackup.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserBackupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserBackupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserBackup.
   * @param {UserBackupUpsertArgs} args - Arguments to update or create a UserBackup.
   * @example
   * // Update or create a UserBackup
   * const userBackup = await prisma.userBackup.upsert({
   *   create: {
   *     // ... data to create a UserBackup
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserBackup we want to update
   *   }
   * })
   */
  upsert<T extends UserBackupUpsertArgs>(args: Prisma.SelectSubset<T, UserBackupUpsertArgs<ExtArgs>>): Prisma.Prisma__UserBackupClient<runtime.Types.Result.GetResult<Prisma.$UserBackupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserBackups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBackupCountArgs} args - Arguments to filter UserBackups to count.
   * @example
   * // Count the number of UserBackups
   * const count = await prisma.userBackup.count({
   *   where: {
   *     // ... the filter for the UserBackups we want to count
   *   }
   * })
  **/
  count<T extends UserBackupCountArgs>(
    args?: Prisma.Subset<T, UserBackupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserBackupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserBackup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBackupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserBackupAggregateArgs>(args: Prisma.Subset<T, UserBackupAggregateArgs>): Prisma.PrismaPromise<GetUserBackupAggregateType<T>>

  /**
   * Group by UserBackup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBackupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserBackupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserBackupGroupByArgs['orderBy'] }
      : { orderBy?: UserBackupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserBackupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserBackupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserBackup model
 */
readonly fields: UserBackupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserBackup.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserBackupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserBackup model
 */
export interface UserBackupFieldRefs {
  readonly id: Prisma.FieldRef<"UserBackup", 'BigInt'>
  readonly originalUserId: Prisma.FieldRef<"UserBackup", 'String'>
  readonly status: Prisma.FieldRef<"UserBackup", 'String'>
  readonly fingerprintId: Prisma.FieldRef<"UserBackup", 'String'>
  readonly clerkUserId: Prisma.FieldRef<"UserBackup", 'String'>
  readonly stripeCusId: Prisma.FieldRef<"UserBackup", 'String'>
  readonly email: Prisma.FieldRef<"UserBackup", 'String'>
  readonly userName: Prisma.FieldRef<"UserBackup", 'String'>
  readonly backupData: Prisma.FieldRef<"UserBackup", 'Json'>
  readonly deletedAt: Prisma.FieldRef<"UserBackup", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"UserBackup", 'DateTime'>
  readonly deleted: Prisma.FieldRef<"UserBackup", 'Int'>
}
    

// Custom InputTypes
/**
 * UserBackup findUnique
 */
export type UserBackupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * Filter, which UserBackup to fetch.
   */
  where: Prisma.UserBackupWhereUniqueInput
}

/**
 * UserBackup findUniqueOrThrow
 */
export type UserBackupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * Filter, which UserBackup to fetch.
   */
  where: Prisma.UserBackupWhereUniqueInput
}

/**
 * UserBackup findFirst
 */
export type UserBackupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * Filter, which UserBackup to fetch.
   */
  where?: Prisma.UserBackupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBackups to fetch.
   */
  orderBy?: Prisma.UserBackupOrderByWithRelationInput | Prisma.UserBackupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBackups.
   */
  cursor?: Prisma.UserBackupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBackups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBackups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBackups.
   */
  distinct?: Prisma.UserBackupScalarFieldEnum | Prisma.UserBackupScalarFieldEnum[]
}

/**
 * UserBackup findFirstOrThrow
 */
export type UserBackupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * Filter, which UserBackup to fetch.
   */
  where?: Prisma.UserBackupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBackups to fetch.
   */
  orderBy?: Prisma.UserBackupOrderByWithRelationInput | Prisma.UserBackupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBackups.
   */
  cursor?: Prisma.UserBackupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBackups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBackups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBackups.
   */
  distinct?: Prisma.UserBackupScalarFieldEnum | Prisma.UserBackupScalarFieldEnum[]
}

/**
 * UserBackup findMany
 */
export type UserBackupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * Filter, which UserBackups to fetch.
   */
  where?: Prisma.UserBackupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBackups to fetch.
   */
  orderBy?: Prisma.UserBackupOrderByWithRelationInput | Prisma.UserBackupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserBackups.
   */
  cursor?: Prisma.UserBackupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBackups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBackups.
   */
  skip?: number
  distinct?: Prisma.UserBackupScalarFieldEnum | Prisma.UserBackupScalarFieldEnum[]
}

/**
 * UserBackup create
 */
export type UserBackupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * The data needed to create a UserBackup.
   */
  data: Prisma.XOR<Prisma.UserBackupCreateInput, Prisma.UserBackupUncheckedCreateInput>
}

/**
 * UserBackup createMany
 */
export type UserBackupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserBackups.
   */
  data: Prisma.UserBackupCreateManyInput | Prisma.UserBackupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserBackup createManyAndReturn
 */
export type UserBackupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * The data used to create many UserBackups.
   */
  data: Prisma.UserBackupCreateManyInput | Prisma.UserBackupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserBackup update
 */
export type UserBackupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * The data needed to update a UserBackup.
   */
  data: Prisma.XOR<Prisma.UserBackupUpdateInput, Prisma.UserBackupUncheckedUpdateInput>
  /**
   * Choose, which UserBackup to update.
   */
  where: Prisma.UserBackupWhereUniqueInput
}

/**
 * UserBackup updateMany
 */
export type UserBackupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserBackups.
   */
  data: Prisma.XOR<Prisma.UserBackupUpdateManyMutationInput, Prisma.UserBackupUncheckedUpdateManyInput>
  /**
   * Filter which UserBackups to update
   */
  where?: Prisma.UserBackupWhereInput
  /**
   * Limit how many UserBackups to update.
   */
  limit?: number
}

/**
 * UserBackup updateManyAndReturn
 */
export type UserBackupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * The data used to update UserBackups.
   */
  data: Prisma.XOR<Prisma.UserBackupUpdateManyMutationInput, Prisma.UserBackupUncheckedUpdateManyInput>
  /**
   * Filter which UserBackups to update
   */
  where?: Prisma.UserBackupWhereInput
  /**
   * Limit how many UserBackups to update.
   */
  limit?: number
}

/**
 * UserBackup upsert
 */
export type UserBackupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * The filter to search for the UserBackup to update in case it exists.
   */
  where: Prisma.UserBackupWhereUniqueInput
  /**
   * In case the UserBackup found by the `where` argument doesn't exist, create a new UserBackup with this data.
   */
  create: Prisma.XOR<Prisma.UserBackupCreateInput, Prisma.UserBackupUncheckedCreateInput>
  /**
   * In case the UserBackup was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserBackupUpdateInput, Prisma.UserBackupUncheckedUpdateInput>
}

/**
 * UserBackup delete
 */
export type UserBackupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
  /**
   * Filter which UserBackup to delete.
   */
  where: Prisma.UserBackupWhereUniqueInput
}

/**
 * UserBackup deleteMany
 */
export type UserBackupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBackups to delete
   */
  where?: Prisma.UserBackupWhereInput
  /**
   * Limit how many UserBackups to delete.
   */
  limit?: number
}

/**
 * UserBackup without action
 */
export type UserBackupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBackup
   */
  select?: Prisma.UserBackupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBackup
   */
  omit?: Prisma.UserBackupOmit<ExtArgs> | null
}
