
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserAvgAggregateOutputType = {
  id: number | null
}

export type UserSumAggregateOutputType = {
  id: bigint | null
}

export type UserMinAggregateOutputType = {
  id: bigint | null
  userId: string | null
  status: string | null
  fingerprintId: string | null
  clerkUserId: string | null
  stripeCusId: string | null
  email: string | null
  userName: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserMaxAggregateOutputType = {
  id: bigint | null
  userId: string | null
  status: string | null
  fingerprintId: string | null
  clerkUserId: string | null
  stripeCusId: string | null
  email: string | null
  userName: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserCountAggregateOutputType = {
  id: number
  userId: number
  status: number
  fingerprintId: number
  clerkUserId: number
  stripeCusId: number
  email: number
  userName: number
  createdAt: number
  updatedAt: number
  sourceRef: number
  _all: number
}


export type UserAvgAggregateInputType = {
  id?: true
}

export type UserSumAggregateInputType = {
  id?: true
}

export type UserMinAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  fingerprintId?: true
  clerkUserId?: true
  stripeCusId?: true
  email?: true
  userName?: true
  createdAt?: true
  updatedAt?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  fingerprintId?: true
  clerkUserId?: true
  stripeCusId?: true
  email?: true
  userName?: true
  createdAt?: true
  updatedAt?: true
}

export type UserCountAggregateInputType = {
  id?: true
  userId?: true
  status?: true
  fingerprintId?: true
  clerkUserId?: true
  stripeCusId?: true
  email?: true
  userName?: true
  createdAt?: true
  updatedAt?: true
  sourceRef?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _avg?: UserAvgAggregateInputType
  _sum?: UserSumAggregateInputType
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: bigint
  userId: string
  status: string
  fingerprintId: string | null
  clerkUserId: string | null
  stripeCusId: string | null
  email: string | null
  userName: string | null
  createdAt: Date | null
  updatedAt: Date | null
  sourceRef: runtime.JsonValue | null
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.BigIntFilter<"User"> | bigint | number
  userId?: Prisma.UuidFilter<"User"> | string
  status?: Prisma.StringFilter<"User"> | string
  fingerprintId?: Prisma.StringNullableFilter<"User"> | string | null
  clerkUserId?: Prisma.StringNullableFilter<"User"> | string | null
  stripeCusId?: Prisma.StringNullableFilter<"User"> | string | null
  email?: Prisma.StringNullableFilter<"User"> | string | null
  userName?: Prisma.StringNullableFilter<"User"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  sourceRef?: Prisma.JsonNullableFilter<"User">
  creditAuditLogs?: Prisma.CreditAuditLogListRelationFilter
  credit?: Prisma.XOR<Prisma.CreditNullableScalarRelationFilter, Prisma.CreditWhereInput> | null
  subscription?: Prisma.XOR<Prisma.SubscriptionNullableScalarRelationFilter, Prisma.SubscriptionWhereInput> | null
  transactions?: Prisma.TransactionListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fingerprintId?: Prisma.SortOrderInput | Prisma.SortOrder
  clerkUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeCusId?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  userName?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  sourceRef?: Prisma.SortOrderInput | Prisma.SortOrder
  creditAuditLogs?: Prisma.CreditAuditLogOrderByRelationAggregateInput
  credit?: Prisma.CreditOrderByWithRelationInput
  subscription?: Prisma.SubscriptionOrderByWithRelationInput
  transactions?: Prisma.TransactionOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  userId?: string
  clerkUserId?: string
  stripeCusId?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  status?: Prisma.StringFilter<"User"> | string
  fingerprintId?: Prisma.StringNullableFilter<"User"> | string | null
  email?: Prisma.StringNullableFilter<"User"> | string | null
  userName?: Prisma.StringNullableFilter<"User"> | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  sourceRef?: Prisma.JsonNullableFilter<"User">
  creditAuditLogs?: Prisma.CreditAuditLogListRelationFilter
  credit?: Prisma.XOR<Prisma.CreditNullableScalarRelationFilter, Prisma.CreditWhereInput> | null
  subscription?: Prisma.XOR<Prisma.SubscriptionNullableScalarRelationFilter, Prisma.SubscriptionWhereInput> | null
  transactions?: Prisma.TransactionListRelationFilter
}, "id" | "userId" | "clerkUserId" | "stripeCusId">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fingerprintId?: Prisma.SortOrderInput | Prisma.SortOrder
  clerkUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeCusId?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  userName?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  sourceRef?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _avg?: Prisma.UserAvgOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
  _sum?: Prisma.UserSumOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"User"> | bigint | number
  userId?: Prisma.UuidWithAggregatesFilter<"User"> | string
  status?: Prisma.StringWithAggregatesFilter<"User"> | string
  fingerprintId?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  clerkUserId?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  stripeCusId?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  userName?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  createdAt?: Prisma.DateTimeNullableWithAggregatesFilter<"User"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"User"> | Date | string | null
  sourceRef?: Prisma.JsonNullableWithAggregatesFilter<"User">
}

export type UserCreateInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogCreateNestedManyWithoutUserInput
  credit?: Prisma.CreditCreateNestedOneWithoutUserInput
  subscription?: Prisma.SubscriptionCreateNestedOneWithoutUserInput
  transactions?: Prisma.TransactionCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUncheckedCreateNestedManyWithoutUserInput
  credit?: Prisma.CreditUncheckedCreateNestedOneWithoutUserInput
  subscription?: Prisma.SubscriptionUncheckedCreateNestedOneWithoutUserInput
  transactions?: Prisma.TransactionUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUpdateManyWithoutUserNestedInput
  credit?: Prisma.CreditUpdateOneWithoutUserNestedInput
  subscription?: Prisma.SubscriptionUpdateOneWithoutUserNestedInput
  transactions?: Prisma.TransactionUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUncheckedUpdateManyWithoutUserNestedInput
  credit?: Prisma.CreditUncheckedUpdateOneWithoutUserNestedInput
  subscription?: Prisma.SubscriptionUncheckedUpdateOneWithoutUserNestedInput
  transactions?: Prisma.TransactionUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fingerprintId?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  stripeCusId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  sourceRef?: Prisma.SortOrder
}

export type UserAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fingerprintId?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  stripeCusId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fingerprintId?: Prisma.SortOrder
  clerkUserId?: Prisma.SortOrder
  stripeCusId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  userName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type UserCreateNestedOneWithoutSubscriptionInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSubscriptionInput, Prisma.UserUncheckedCreateWithoutSubscriptionInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSubscriptionInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutSubscriptionNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSubscriptionInput, Prisma.UserUncheckedCreateWithoutSubscriptionInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSubscriptionInput
  upsert?: Prisma.UserUpsertWithoutSubscriptionInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutSubscriptionInput, Prisma.UserUpdateWithoutSubscriptionInput>, Prisma.UserUncheckedUpdateWithoutSubscriptionInput>
}

export type UserCreateNestedOneWithoutCreditInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreditInput, Prisma.UserUncheckedCreateWithoutCreditInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreditInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCreditNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreditInput, Prisma.UserUncheckedCreateWithoutCreditInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreditInput
  upsert?: Prisma.UserUpsertWithoutCreditInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCreditInput, Prisma.UserUpdateWithoutCreditInput>, Prisma.UserUncheckedUpdateWithoutCreditInput>
}

export type UserCreateNestedOneWithoutTransactionsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutTransactionsInput, Prisma.UserUncheckedCreateWithoutTransactionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutTransactionsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutTransactionsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutTransactionsInput, Prisma.UserUncheckedCreateWithoutTransactionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutTransactionsInput
  upsert?: Prisma.UserUpsertWithoutTransactionsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutTransactionsInput, Prisma.UserUpdateWithoutTransactionsInput>, Prisma.UserUncheckedUpdateWithoutTransactionsInput>
}

export type UserCreateNestedOneWithoutCreditAuditLogsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreditAuditLogsInput, Prisma.UserUncheckedCreateWithoutCreditAuditLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreditAuditLogsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCreditAuditLogsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreditAuditLogsInput, Prisma.UserUncheckedCreateWithoutCreditAuditLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreditAuditLogsInput
  upsert?: Prisma.UserUpsertWithoutCreditAuditLogsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCreditAuditLogsInput, Prisma.UserUpdateWithoutCreditAuditLogsInput>, Prisma.UserUncheckedUpdateWithoutCreditAuditLogsInput>
}

export type UserCreateWithoutSubscriptionInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogCreateNestedManyWithoutUserInput
  credit?: Prisma.CreditCreateNestedOneWithoutUserInput
  transactions?: Prisma.TransactionCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutSubscriptionInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUncheckedCreateNestedManyWithoutUserInput
  credit?: Prisma.CreditUncheckedCreateNestedOneWithoutUserInput
  transactions?: Prisma.TransactionUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutSubscriptionInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutSubscriptionInput, Prisma.UserUncheckedCreateWithoutSubscriptionInput>
}

export type UserUpsertWithoutSubscriptionInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutSubscriptionInput, Prisma.UserUncheckedUpdateWithoutSubscriptionInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutSubscriptionInput, Prisma.UserUncheckedCreateWithoutSubscriptionInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutSubscriptionInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutSubscriptionInput, Prisma.UserUncheckedUpdateWithoutSubscriptionInput>
}

export type UserUpdateWithoutSubscriptionInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUpdateManyWithoutUserNestedInput
  credit?: Prisma.CreditUpdateOneWithoutUserNestedInput
  transactions?: Prisma.TransactionUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutSubscriptionInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUncheckedUpdateManyWithoutUserNestedInput
  credit?: Prisma.CreditUncheckedUpdateOneWithoutUserNestedInput
  transactions?: Prisma.TransactionUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutCreditInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogCreateNestedManyWithoutUserInput
  subscription?: Prisma.SubscriptionCreateNestedOneWithoutUserInput
  transactions?: Prisma.TransactionCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutCreditInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUncheckedCreateNestedManyWithoutUserInput
  subscription?: Prisma.SubscriptionUncheckedCreateNestedOneWithoutUserInput
  transactions?: Prisma.TransactionUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutCreditInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCreditInput, Prisma.UserUncheckedCreateWithoutCreditInput>
}

export type UserUpsertWithoutCreditInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCreditInput, Prisma.UserUncheckedUpdateWithoutCreditInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCreditInput, Prisma.UserUncheckedCreateWithoutCreditInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCreditInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCreditInput, Prisma.UserUncheckedUpdateWithoutCreditInput>
}

export type UserUpdateWithoutCreditInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUpdateManyWithoutUserNestedInput
  subscription?: Prisma.SubscriptionUpdateOneWithoutUserNestedInput
  transactions?: Prisma.TransactionUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutCreditInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUncheckedUpdateManyWithoutUserNestedInput
  subscription?: Prisma.SubscriptionUncheckedUpdateOneWithoutUserNestedInput
  transactions?: Prisma.TransactionUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutTransactionsInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogCreateNestedManyWithoutUserInput
  credit?: Prisma.CreditCreateNestedOneWithoutUserInput
  subscription?: Prisma.SubscriptionCreateNestedOneWithoutUserInput
}

export type UserUncheckedCreateWithoutTransactionsInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUncheckedCreateNestedManyWithoutUserInput
  credit?: Prisma.CreditUncheckedCreateNestedOneWithoutUserInput
  subscription?: Prisma.SubscriptionUncheckedCreateNestedOneWithoutUserInput
}

export type UserCreateOrConnectWithoutTransactionsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutTransactionsInput, Prisma.UserUncheckedCreateWithoutTransactionsInput>
}

export type UserUpsertWithoutTransactionsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutTransactionsInput, Prisma.UserUncheckedUpdateWithoutTransactionsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutTransactionsInput, Prisma.UserUncheckedCreateWithoutTransactionsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutTransactionsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutTransactionsInput, Prisma.UserUncheckedUpdateWithoutTransactionsInput>
}

export type UserUpdateWithoutTransactionsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUpdateManyWithoutUserNestedInput
  credit?: Prisma.CreditUpdateOneWithoutUserNestedInput
  subscription?: Prisma.SubscriptionUpdateOneWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutTransactionsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  creditAuditLogs?: Prisma.CreditAuditLogUncheckedUpdateManyWithoutUserNestedInput
  credit?: Prisma.CreditUncheckedUpdateOneWithoutUserNestedInput
  subscription?: Prisma.SubscriptionUncheckedUpdateOneWithoutUserNestedInput
}

export type UserCreateWithoutCreditAuditLogsInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  credit?: Prisma.CreditCreateNestedOneWithoutUserInput
  subscription?: Prisma.SubscriptionCreateNestedOneWithoutUserInput
  transactions?: Prisma.TransactionCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutCreditAuditLogsInput = {
  id?: bigint | number
  userId?: string
  status?: string
  fingerprintId?: string | null
  clerkUserId?: string | null
  stripeCusId?: string | null
  email?: string | null
  userName?: string | null
  createdAt?: Date | string | null
  updatedAt?: Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  credit?: Prisma.CreditUncheckedCreateNestedOneWithoutUserInput
  subscription?: Prisma.SubscriptionUncheckedCreateNestedOneWithoutUserInput
  transactions?: Prisma.TransactionUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutCreditAuditLogsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCreditAuditLogsInput, Prisma.UserUncheckedCreateWithoutCreditAuditLogsInput>
}

export type UserUpsertWithoutCreditAuditLogsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCreditAuditLogsInput, Prisma.UserUncheckedUpdateWithoutCreditAuditLogsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCreditAuditLogsInput, Prisma.UserUncheckedCreateWithoutCreditAuditLogsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCreditAuditLogsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCreditAuditLogsInput, Prisma.UserUncheckedUpdateWithoutCreditAuditLogsInput>
}

export type UserUpdateWithoutCreditAuditLogsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  credit?: Prisma.CreditUpdateOneWithoutUserNestedInput
  subscription?: Prisma.SubscriptionUpdateOneWithoutUserNestedInput
  transactions?: Prisma.TransactionUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutCreditAuditLogsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprintId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clerkUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeCusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sourceRef?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  credit?: Prisma.CreditUncheckedUpdateOneWithoutUserNestedInput
  subscription?: Prisma.SubscriptionUncheckedUpdateOneWithoutUserNestedInput
  transactions?: Prisma.TransactionUncheckedUpdateManyWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  creditAuditLogs: number
  transactions: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creditAuditLogs?: boolean | UserCountOutputTypeCountCreditAuditLogsArgs
  transactions?: boolean | UserCountOutputTypeCountTransactionsArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCreditAuditLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CreditAuditLogWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountTransactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransactionWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  fingerprintId?: boolean
  clerkUserId?: boolean
  stripeCusId?: boolean
  email?: boolean
  userName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sourceRef?: boolean
  creditAuditLogs?: boolean | Prisma.User$creditAuditLogsArgs<ExtArgs>
  credit?: boolean | Prisma.User$creditArgs<ExtArgs>
  subscription?: boolean | Prisma.User$subscriptionArgs<ExtArgs>
  transactions?: boolean | Prisma.User$transactionsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  fingerprintId?: boolean
  clerkUserId?: boolean
  stripeCusId?: boolean
  email?: boolean
  userName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sourceRef?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  status?: boolean
  fingerprintId?: boolean
  clerkUserId?: boolean
  stripeCusId?: boolean
  email?: boolean
  userName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sourceRef?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  userId?: boolean
  status?: boolean
  fingerprintId?: boolean
  clerkUserId?: boolean
  stripeCusId?: boolean
  email?: boolean
  userName?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sourceRef?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "status" | "fingerprintId" | "clerkUserId" | "stripeCusId" | "email" | "userName" | "createdAt" | "updatedAt" | "sourceRef", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creditAuditLogs?: boolean | Prisma.User$creditAuditLogsArgs<ExtArgs>
  credit?: boolean | Prisma.User$creditArgs<ExtArgs>
  subscription?: boolean | Prisma.User$subscriptionArgs<ExtArgs>
  transactions?: boolean | Prisma.User$transactionsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    creditAuditLogs: Prisma.$CreditAuditLogPayload<ExtArgs>[]
    credit: Prisma.$CreditPayload<ExtArgs> | null
    subscription: Prisma.$SubscriptionPayload<ExtArgs> | null
    transactions: Prisma.$TransactionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    userId: string
    status: string
    fingerprintId: string | null
    clerkUserId: string | null
    stripeCusId: string | null
    email: string | null
    userName: string | null
    createdAt: Date | null
    updatedAt: Date | null
    sourceRef: runtime.JsonValue | null
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  creditAuditLogs<T extends Prisma.User$creditAuditLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$creditAuditLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CreditAuditLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  credit<T extends Prisma.User$creditArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$creditArgs<ExtArgs>>): Prisma.Prisma__CreditClient<runtime.Types.Result.GetResult<Prisma.$CreditPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  subscription<T extends Prisma.User$subscriptionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$subscriptionArgs<ExtArgs>>): Prisma.Prisma__SubscriptionClient<runtime.Types.Result.GetResult<Prisma.$SubscriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  transactions<T extends Prisma.User$transactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$transactionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'BigInt'>
  readonly userId: Prisma.FieldRef<"User", 'String'>
  readonly status: Prisma.FieldRef<"User", 'String'>
  readonly fingerprintId: Prisma.FieldRef<"User", 'String'>
  readonly clerkUserId: Prisma.FieldRef<"User", 'String'>
  readonly stripeCusId: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly userName: Prisma.FieldRef<"User", 'String'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly sourceRef: Prisma.FieldRef<"User", 'Json'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data?: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.creditAuditLogs
 */
export type User$creditAuditLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CreditAuditLog
   */
  select?: Prisma.CreditAuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CreditAuditLog
   */
  omit?: Prisma.CreditAuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditAuditLogInclude<ExtArgs> | null
  where?: Prisma.CreditAuditLogWhereInput
  orderBy?: Prisma.CreditAuditLogOrderByWithRelationInput | Prisma.CreditAuditLogOrderByWithRelationInput[]
  cursor?: Prisma.CreditAuditLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CreditAuditLogScalarFieldEnum | Prisma.CreditAuditLogScalarFieldEnum[]
}

/**
 * User.credit
 */
export type User$creditArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Credit
   */
  select?: Prisma.CreditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Credit
   */
  omit?: Prisma.CreditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreditInclude<ExtArgs> | null
  where?: Prisma.CreditWhereInput
}

/**
 * User.subscription
 */
export type User$subscriptionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subscription
   */
  select?: Prisma.SubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subscription
   */
  omit?: Prisma.SubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubscriptionInclude<ExtArgs> | null
  where?: Prisma.SubscriptionWhereInput
}

/**
 * User.transactions
 */
export type User$transactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  where?: Prisma.TransactionWhereInput
  orderBy?: Prisma.TransactionOrderByWithRelationInput | Prisma.TransactionOrderByWithRelationInput[]
  cursor?: Prisma.TransactionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransactionScalarFieldEnum | Prisma.TransactionScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
