
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  Subscription: 'Subscription',
  Credit: 'Credit',
  Transaction: 'Transaction',
  CreditAuditLog: 'CreditAuditLog',
  UserBackup: 'UserBackup',
  Apilog: 'Apilog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  fingerprintId: 'fingerprintId',
  clerkUserId: 'clerkUserId',
  stripeCusId: 'stripeCusId',
  email: 'email',
  userName: 'userName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  sourceRef: 'sourceRef'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  paySubscriptionId: 'paySubscriptionId',
  orderId: 'orderId',
  priceId: 'priceId',
  priceName: 'priceName',
  creditsAllocated: 'creditsAllocated',
  subPeriodStart: 'subPeriodStart',
  subPeriodEnd: 'subPeriodEnd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deleted: 'deleted'
} as const

export type SubscriptionScalarFieldEnum = (typeof SubscriptionScalarFieldEnum)[keyof typeof SubscriptionScalarFieldEnum]


export const CreditScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  balanceFree: 'balanceFree',
  totalFreeLimit: 'totalFreeLimit',
  freeStart: 'freeStart',
  freeEnd: 'freeEnd',
  balancePaid: 'balancePaid',
  totalPaidLimit: 'totalPaidLimit',
  paidStart: 'paidStart',
  paidEnd: 'paidEnd',
  balanceOneTimePaid: 'balanceOneTimePaid',
  totalOneTimePaidLimit: 'totalOneTimePaidLimit',
  oneTimePaidStart: 'oneTimePaidStart',
  oneTimePaidEnd: 'oneTimePaidEnd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CreditScalarFieldEnum = (typeof CreditScalarFieldEnum)[keyof typeof CreditScalarFieldEnum]


export const TransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  orderId: 'orderId',
  orderStatus: 'orderStatus',
  orderCreatedAt: 'orderCreatedAt',
  orderExpiredAt: 'orderExpiredAt',
  orderUpdatedAt: 'orderUpdatedAt',
  type: 'type',
  paySupplier: 'paySupplier',
  paySessionId: 'paySessionId',
  payTransactionId: 'payTransactionId',
  paySubscriptionId: 'paySubscriptionId',
  subPeriodStart: 'subPeriodStart',
  subPeriodEnd: 'subPeriodEnd',
  subLastTryCancelAt: 'subLastTryCancelAt',
  subPeriodCanceledAt: 'subPeriodCanceledAt',
  subCancellationDetail: 'subCancellationDetail',
  priceId: 'priceId',
  priceName: 'priceName',
  amount: 'amount',
  currency: 'currency',
  creditsGranted: 'creditsGranted',
  payInvoiceId: 'payInvoiceId',
  paymentStatus: 'paymentStatus',
  billingReason: 'billingReason',
  hostedInvoiceUrl: 'hostedInvoiceUrl',
  invoicePdf: 'invoicePdf',
  orderDetail: 'orderDetail',
  paidEmail: 'paidEmail',
  paidAt: 'paidAt',
  paidDetail: 'paidDetail',
  payUpdatedAt: 'payUpdatedAt',
  deleted: 'deleted'
} as const

export type TransactionScalarFieldEnum = (typeof TransactionScalarFieldEnum)[keyof typeof TransactionScalarFieldEnum]


export const CreditAuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  creditsChange: 'creditsChange',
  feature: 'feature',
  creditType: 'creditType',
  operationType: 'operationType',
  operationReferId: 'operationReferId',
  createdAt: 'createdAt',
  deleted: 'deleted'
} as const

export type CreditAuditLogScalarFieldEnum = (typeof CreditAuditLogScalarFieldEnum)[keyof typeof CreditAuditLogScalarFieldEnum]


export const UserBackupScalarFieldEnum = {
  id: 'id',
  originalUserId: 'originalUserId',
  status: 'status',
  fingerprintId: 'fingerprintId',
  clerkUserId: 'clerkUserId',
  stripeCusId: 'stripeCusId',
  email: 'email',
  userName: 'userName',
  backupData: 'backupData',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  deleted: 'deleted'
} as const

export type UserBackupScalarFieldEnum = (typeof UserBackupScalarFieldEnum)[keyof typeof UserBackupScalarFieldEnum]


export const ApilogScalarFieldEnum = {
  id: 'id',
  apiType: 'apiType',
  methodName: 'methodName',
  summary: 'summary',
  request: 'request',
  response: 'response',
  createdAt: 'createdAt'
} as const

export type ApilogScalarFieldEnum = (typeof ApilogScalarFieldEnum)[keyof typeof ApilogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

