import fs from 'node:fs/promises';
import path from 'node:path';
import type { StandardSchemaV1 } from '@standard-schema/spec';
import { createStorage } from '../storage';
import { createMarkdownCompiler } from '../md/compiler';
import { serializeCompileResult } from '../md/render-shared';
import { getLocalMdDurationMs, getLocalMdNow, logLocalMdDebug } from '../debug';
import type { CreateLocalMdSourceLoaderOptions } from '../server/source-shared';
import { resolveSourceDir } from '../server/source-shared';
import type {
  BuiltSourceManifestEntry,
  BuiltSourceMetaEntry,
  BuiltSourceModuleArtifact,
  BuiltSourcePageEntry,
} from './types';

export interface BuildLocalMdSourceOptions<
  FrontmatterSchema extends StandardSchemaV1 = StandardSchemaV1,
  MetaSchema extends StandardSchemaV1 = StandardSchemaV1,
> extends Omit<CreateLocalMdSourceLoaderOptions<FrontmatterSchema, MetaSchema>, 'i18n' | 'icon' | 'mode'> {
  appRoot?: string;
}

export interface BuildLocalMdSourcesOptions<
  FrontmatterSchema extends StandardSchemaV1 = StandardSchemaV1,
  MetaSchema extends StandardSchemaV1 = StandardSchemaV1,
> extends Omit<BuildLocalMdSourceOptions<FrontmatterSchema, MetaSchema>, 'sourceKey'> {
  sourceKeys: readonly string[];
}

export async function buildLocalMdSource<
  FrontmatterSchema extends StandardSchemaV1 = StandardSchemaV1,
  MetaSchema extends StandardSchemaV1 = StandardSchemaV1,
>(
  options: BuildLocalMdSourceOptions<FrontmatterSchema, MetaSchema>,
) {
  const startedAt = getLocalMdNow();
  const {
    sourceKey = 'docs',
    dir,
    sourceRootDir,
    appRoot = process.cwd(),
    ...config
  } = options;

  const resolvedDir = resolveSourceDir(sourceKey, dir, sourceRootDir);
  const sourceOutputDir = path.join(appRoot, '.source');
  const sourceModuleFileName = `${sourceKey}.source.config.mjs`;
  const sourceModulePath = path.join(sourceOutputDir, sourceModuleFileName);
  const sourceIndexPath = path.join(sourceOutputDir, 'index.ts');

  await fs.mkdir(sourceOutputDir, { recursive: true });

  const storage = createStorage({
    dir: resolvedDir,
    ...config,
  });
  const compiler = createMarkdownCompiler(config);
  const { pages, metas } = await storage.getPages();

  const pageEntries: BuiltSourcePageEntry[] = [];
  const metaEntries: BuiltSourceMetaEntry[] = metas.map((meta) => ({
    path: meta.path,
    absolutePath: meta.absolutePath,
    data: meta.data as Record<string, unknown>,
  }));

  for (const page of pages) {
    const compiled = await compiler.compile({
      path: page.absolutePath,
      value: page.content,
      data: { frontmatter: page.frontmatter },
    });

    pageEntries.push({
      path: page.path,
      absolutePath: page.absolutePath,
      title: page.title,
      description: page.description,
      icon: page.icon,
      frontmatter: toRecord(page.frontmatter),
      toc: compiled.file.data.rehypeToc as any[] | undefined,
      structuredData: compiled.file.data.structuredData as BuiltSourcePageEntry['structuredData'],
      compiled: serializeCompileResult(compiled),
    });
  }

  const moduleArtifact: BuiltSourceModuleArtifact = {
    sourceKey,
    dir: resolvedDir,
    pages: pageEntries,
    metas: metaEntries,
  };

  await fs.writeFile(
    sourceModulePath,
    createSourceModuleContent(moduleArtifact),
    'utf8',
  );

  await upsertSourceIndexEntry(sourceIndexPath, {
    sourceKey,
    importPath: `./${sourceModuleFileName}`,
  });

  logLocalMdDebug('buildLocalMdSource:complete', {
    sourceKey,
    resolvedDir,
    sourceOutputDir,
    sourceModulePath,
    pageFileCount: pageEntries.length,
    metaFileCount: metaEntries.length,
    durationMs: getLocalMdDurationMs(startedAt),
  });

  return {
    outputDir: sourceOutputDir,
    moduleFilePath: sourceModulePath,
    moduleArtifact,
  };
}

export async function buildLocalMdSources<
  FrontmatterSchema extends StandardSchemaV1 = StandardSchemaV1,
  MetaSchema extends StandardSchemaV1 = StandardSchemaV1,
>(
  options: BuildLocalMdSourcesOptions<FrontmatterSchema, MetaSchema>,
) {
  const { sourceKeys, ...sharedOptions } = options;
  const results = [];

  for (const sourceKey of sourceKeys) {
    results.push(await buildLocalMdSource({
      sourceKey,
      ...sharedOptions,
    }));
  }

  return results;
}

function createSourceModuleContent(artifact: BuiltSourceModuleArtifact) {
  return [
    '// This file is generated by @windrun-huaiin/fumadocs-local-md.',
    `const source = ${JSON.stringify(artifact, null, 2)};`,
    'export default source;',
    '',
  ].join('\n');
}

async function upsertSourceIndexEntry(
  sourceIndexPath: string,
  entry: BuiltSourceManifestEntry,
) {
  const entries = await readSourceIndexEntries(sourceIndexPath);
  const nextEntries = [
    ...entries.filter((item) => item.sourceKey !== entry.sourceKey),
    entry,
  ].sort((a, b) => a.sourceKey.localeCompare(b.sourceKey));

  await fs.writeFile(
    sourceIndexPath,
    createSourceIndexContent(nextEntries),
    'utf8',
  );
}

async function readSourceIndexEntries(sourceIndexPath: string) {
  try {
    const content = await fs.readFile(sourceIndexPath, 'utf8');
    const pattern = /export \{ default as ([A-Za-z0-9_]+) \} from ['"](.+)['"];?/g;
    const entries: BuiltSourceManifestEntry[] = [];
    let match: RegExpExecArray | null;

    while ((match = pattern.exec(content)) != null) {
      entries.push({
        sourceKey: match[1],
        importPath: match[2],
      });
    }

    return entries;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return [];
    }

    throw error;
  }
}

function createSourceIndexContent(entries: BuiltSourceManifestEntry[]) {
  return [
    '// This file is generated by @windrun-huaiin/fumadocs-local-md.',
    ...entries.map((entry) => `export { default as ${entry.sourceKey} } from '${entry.importPath}';`),
    '',
  ].join('\n');
}

function toRecord(value: unknown): Record<string, unknown> {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return {};
}
